### ISSUE TITLE
Uncaught Error: Class 'Laravel\Tinker\ClassAliasAutoloader' not found

### ISSUE THREAD

**Issue by mendelsimon** [Roboroads/laravel-tinker#12]
```
// Laravel Tinker started at 2020-09-04 11:18:43
PHP Fatal error:  Uncaught Error: Class 'Laravel\Tinker\ClassAliasAutoloader' not found in Command line code:38
Stack trace:
#0 {main}
  thrown in Command line code on line 38

                                                                                                 
  [Symfony\Component\Debug\Exception\FatalErrorException]                                        
  Uncaught Error: Class 'Laravel\Tinker\ClassAliasAutoloader' not found in Command line code:38  
  Stack trace:                                                                                   
  #0 {main}                                                                                      
    thrown                                                                                       
                                                                                                 



*** Execution finished ***
```

**Comment by Roboroads** [comment]
Hey, what version of Laravel are you on?

**Comment by mendelsimon** [comment]
Laravel 5.3.20 with PHP 7.1.28 on Windows.

**Comment by Roboroads** [comment]
Well, there is the problem. I'm using the underlying laravel tinker package (https://github.com/laravel/tinker). Laravel Tinker was introduced in Laravel 5.4 (tinker 1.0 btw, I have only tested it with tinker 2 which came with Laravel 6)

You should consider upgrading to a higher laravel version.

**Comment by mendelsimon** [comment]
I can definitely use Tinker in Laravel 5.3.20 with `php artisan tinker`.

**Comment by Roboroads** [comment]
What is your tinker version? (`composer show laravel/tinker`)

**Comment by mendelsimon** [comment]
Running that command gives me
```
[InvalidArgumentException]
Package laravel/tinker not found
```
It looks like Tinker used to be a part of `laravel/framework` before 5.4, where it was removed into its own `laravel/tinker` package: https://github.com/laravel/framework/pull/17002.

**Comment by Roboroads** [comment]
Ah, seems like it. I think the scope of this bug goes a little over what I want to support. Laravel ended support for 5.3 a long time ago (August 23rd, 2017). I'm willing to fix bugs that occur in currently supported versions.

If you really want to support your edge case, you may create a PR for it :)

**Comment by Roboroads** [comment]
@mendelsimon I will add an if araound the classloader (#20) so your application will probably also work in v1.1.2 - note that autoloading is probably not going to work, but i'm not sure and am also not officially supporting it.
