### ISSUE TITLE
Remote php interpreter  Laravel root directory problem

### ISSUE THREAD

**Issue by Guilhem-DELAITRE** [Roboroads/laravel-tinker#120]
Stange problem here : 

My setup is as follow : my php interpreter is "remote" : ssh connection to a local running VM

It so happens that when i try to run the tinker console, I got this phpstorm notification : 
"The configured laravel root is not a directory
Please check if it's the right path. Using a guessed vendor path for now."

The strange thing is that if I take the path in "Laravel root folder", and put "cd path" in my .bashrc, it actually works, which means that the directory definetely exists.

I looked in the repository and came to this  ([PhpArtisanTinkerUtil.kt](https://github.com/Roboroads/laravel-tinker/blob/df2768e9bb4350f39ec736d6d648f7d1c029fe0a/src/main/kotlin/nl/deschepers/laraveltinker/util/PhpArtisanTinkerUtil.kt) line 56)
```
if (projectSettings.laravelRoot.isNotEmpty()) {
    val customLaravelRoot = File(projectSettings.laravelRoot)
    
    if (customLaravelRoot.exists() && customLaravelRoot.isDirectory) {
        val customComposerDir = File(customLaravelRoot.path + "/vendor")
        
        if (customComposerDir.exists() && customComposerDir.isDirectory) {
            laravelRoot = projectSettings.laravelRoot
        } else {
            LaravelRootDoesNotHaveVendorBalloon(project).show()
        }
    } else {
        LaravelRootDoesNotExistBalloon(project).show()
    }
}
```
As far as I understand it (not that much), this is for local php interpreter, and I didn't find anything related to remote : 
did I missed something ?

**Comment by Roboroads** [comment]
This issue is now released and accepted! You can update via your IDE plugins settings :)
