### ISSUE TITLE
Add Rerun button on console output

### ISSUE THREAD

**Issue by PanjiNamjaElf** [Roboroads/laravel-tinker#127]
**Is your feature request related to a problem? Please describe.**
When I am done write long code to run on Laravel tinker, I need to scroll up again to rerun the code.

![image](https://user-images.githubusercontent.com/16651293/142955768-5a6218e5-81c0-4c94-b2c3-c12e4586a1b3.png)

**Describe the solution you'd like**
I want request to add rerun button on console output so it will be more practice to rerun the script using Laravel Tinker like this.

![image](https://user-images.githubusercontent.com/16651293/142955884-0be24917-9b2b-4d2d-93b9-7860fb2d6127.png)

![image](https://user-images.githubusercontent.com/16651293/142955680-5ae5c088-2da5-48b5-8f1a-1fe542314870.png)

**Comment by Roboroads** [comment]
If the shortkey (Ctrl+Shift+T) and the toolwindow is not enough yet, you are free to send a PR in for this one :)
