### ISSUE TITLE
Add support for custom "Run Tinker with using custom command"

### ISSUE THREAD

**Issue by rshaw5** [Roboroads/laravel-tinker#129]
### Background
Recently, my team split our app into a few Docker containers. Prior to this, I was using PHPStorm Laravel Tinker extensively with an interpreter installed globally on my machine.

Now that we've moved to Docker, I'd like to also change my PHP interpreter to use our Docker's binary instead of my local machine's (for consistency). I've been able to set my interpreter to Docker, but when I run Laravel Tinker I don't see anything in the output panel.

#### An example
<img width="838" alt="image" src="https://user-images.githubusercontent.com/34202597/143298952-f3d6a988-4772-4a95-be34-de9df4968469.png">

#### Interpreter Settings
<img width="721" alt="image" src="https://user-images.githubusercontent.com/34202597/143299398-3a6ea951-8bf4-46d5-8108-b843512b416c.png">

### Requested Feature
Per [Roboroad's comment](https://github.com/Roboroads/laravel-tinker/issues/46#issuecomment-788010131), I would find it very helpful to be able to set Laravel Tinker to run with a custom command (e.g. A setting to tell Laravel Tinker to run its commands via `./vendor/bin/sail php artisan tinker`)

The ultimate goal of this feature request is to get an output in the output panel when using a PHP interpreter inside a Docker container.  

### Possible Alternatives
_I will update this section if I come up with any alternative ideas._
- Nothing to see here yet

**Comment by rshaw5** [comment]
I didn't see an issue created for the associated bug report yet, per [this comment](https://github.com/Roboroads/laravel-tinker/issues/46#issuecomment-923893637), so I went ahead and created it since this would be a very useful feature in my use case!

**Comment by Roboroads** [comment]
> A setting to tell Laravel Tinker to run its commands via ./vendor/bin/sail php artisan tinker

Note that the plugin never actually runs `php artisan tinker`, rather `php -r <init code> <your code>`. This is using the interpreter PHPstorm uses.

Please check your settings of your PHP Interpreter and path mapping again, All the people I have spoken to have [the same problem, but fixed it with using correct settings](https://github.com/Roboroads/laravel-tinker/issues/132#issuecomment-1012158079)

**Comment by rshaw5** [comment]
Thanks for your reply! I've confirmed that there's _something_ wrong with my path mapping, but I'm not sure what. I'm using Laravel Sail, so maybe that's introducing an issue...

![image](https://user-images.githubusercontent.com/34202597/151027773-53fd3202-3f2a-40c6-aa99-3a9c09d6cf36.png)

<img width="836" alt="Screen Shot 2022-01-25 at 12 27 56 PM" src="https://user-images.githubusercontent.com/34202597/151028267-29b98b37-26a0-476e-a0ca-a13b4148268f.png">

**Comment by Roboroads** [comment]
Oh, fun fact, i have this problem myself now - my laravel project is in a subfolder from the larger project. Might be something to do with that.

**Comment by Lukasss93** [comment]
same problem... (laravel in subfolder + docker php):

![image](https://user-images.githubusercontent.com/4071613/153155210-919de787-1464-4be1-a390-86cfea56ac7b.png)

**Comment by adrianpaiva1** [comment]
I have the same issue, any workarounds>?

**Comment by splaa** [comment]
I have the same problem do you have any ideas?

**Comment by Roboroads** [comment]
@rshaw5 I just helped someone who also had problems with sail. Here's some insights:
 
 - If you have a docker-compose.yml file - do not use the docker interpreter, but the docker-compose interpreter.
 - Make sure your path mappings are correc under the PHP settings.
 - There now is a setting in which you can specify a project root. Make sure this is the path on your docker conntainer.
 - There is a bug present in the current JB products: [read this](https://github.com/Roboroads/laravel-tinker/issues/167)
 
 If you still have problems and are on EAP - if you're up for a call + screenshare so I can help let me know on Discord (Roboroads#1337)

**Comment by nickescobedo** [comment]
@Roboroads your last comment solved it for me using the docker compose file.
