### ISSUE TITLE
Live Output

### ISSUE THREAD

**Issue by AveZomer** [Roboroads/laravel-tinker#131]
Could you make output like a live object.
With possibility to hide and show any keys of object.

Maybe something like this:
<img width="456" alt="Screenshot 2021-12-17 at 15 27 10" src="https://user-images.githubusercontent.com/66947751/146551470-70abc7f3-445f-42c4-a862-b91770fa24fb.png">
.

**Comment by Roboroads** [comment]
I like the idea. I'm going to keep this one open if I (or someone) ever feels like making this.
