### ISSUE TITLE
File name or extension is too long

### ISSUE THREAD

**Issue by Muetze42** [Roboroads/laravel-tinker#134]
**Bug description**
When I run Tinker I get this error message:
`Cannot run program "C:\xampp\php74\php.exe" (in directory "C:\xampp\htdocs\devlabor\ares\ares-residential-report-backend"): CreateProcess error=206, Der Dateiname oder die Erweiterung ist zu lang. To fix it change project interpreter or check settings.`

`Der Dateiname oder die Erweiterung ist zu lang` = `The file name or extension is too long`

**Environment (please complete the following information):**
 - PHPStorm 2021.2.3
 - PHP 8.0 or PHP 7.4
 - Windows 10
 - Laravel Tinker plugin version : 2.31
 - Interpreter Type: XAMPP/PHP for Windows
 - Laravel Version: 7.23.0 & 8.80.0
 - Tinker version: 2.4.1 & 2.7.0

**Comment by Roboroads** [comment]
Windows has a file path length limit - can you check how much characters the path to your vendor directory is?

**Comment by Muetze42** [comment]
Sorry for my late reply...

The limit is disabled. Strangely enough, it worked again the next day without me changing anything. :confused:
