### ISSUE TITLE
Object of class Illuminate\Foundation\Application could not be converted to string

### ISSUE THREAD

**Issue by Roboroads** [Roboroads/laravel-tinker#14]
**Bug description**
When running, in yet unknown conditions, an error occurs.
`PHP Fatal Error: Uncaught Error: Object of class Illuminate\Foundation\Application could not be converted to string in Command line code:6`

**To Reproduce**
Run a tinker console window

**Expected behavior**
The error should not have appeared and output following my code in

**Screenshots**
None

**Environment (please complete the following information):**
 - IDE & Version: PHPStorm 2020.2.1
 - PHP Version: 7.4
 - Interpreter Type: Docker
 - Laravel Version: 7.3.0
 - Tinker version: 2.3.0

**Additional context**
It seems to work with docker run, but not with docker exec in one of my projects.

**Comment by canvural** [comment]
I can also confirm it only happens if `docker exec` is used.

**Comment by Roboroads** [comment]
> I can also confirm it only happens if `docker exec` is used.

Thanks! That helps. 
Now to find out *why* :P

**Comment by Roboroads** [comment]
The script does `$app = require_once(__DIR__ . '/bootstrap/app.php');` and for some reason, passing that into a `docker exec` from PhpStorm makes php think it needs to parse it to a string. For some reason I think this is a bug within PHPStorm and how they pass it to the CLI.

**Comment by JerryBels** [comment]
Hello! Testing again your plugin after you resolved https://github.com/Roboroads/laravel-tinker/issues/46 I now face this issue. 

```
PHP Fatal error:  Uncaught Error: Object of class Illuminate\Foundation\Application could not be converted to string in Command line code:8
Stack trace:
#0 {main}
  thrown in Command line code on line 8
255
```

As I said on the other issue, I'm working on Windows with a Sail environment. The cli interpreter seems fine to me, as well as the path maping. If you need more informations, please ask.

**Comment by Roboroads** [comment]
Yes, this is not fixed as said in the release notes:

> This does not fix the "string conversion" error found when using docker exec. You still have to use docker run for now.

**Comment by Roboroads** [comment]
I found a way to proof to JetBrains this is also a double-dollar-escaping bug.

```
"[docker-compose://[/home/robbin/Robbox/Werkmap/Wereldrestaurant Puur/project-panda/docker-compose.yml]:service-php/]:php" -dxdebug.mode=debug -dxdebug.client_port=9000 -dxdebug.client_host=172.17.0.1 -r eval('var_dump('.chr(36).'argv[1]);'); "$x = 123;"
string(10) "$$x = 123;"
```

Sent this to JB - might get fixed in 2022.2 ^^

**Comment by Roboroads** [comment]
JB 2022.2 fixes this. Closing.

**Comment by hertzelarmengolbf** [comment]
Tested with 2022.3 and still sees this as a problem, running app inside a docker container

// Laravel Tinker started at 2022-09-07 20:02:39
                                                            

Fatal error: Uncaught Error: Object of class Illuminate\Foundation\Application could not be converted to string in Command line code:8
Stack trace:
#0 {main}
  thrown in Command line code on line 8
ERROR: 255

*** Execution finished ***

**Comment by Roboroads** [comment]
@hertzelarmengolbf You might want to check your version again. 2022.3 is not out yet, not even as beta :P
