### ISSUE TITLE
When I switch projects it doesn't work

### ISSUE THREAD

**Issue by gakkiismywife** [Roboroads/laravel-tinker#151]
**Bug description**
When I switch projects it doesn't work

**Comment by Roboroads** [comment]
When I switch projects it does work..

**Comment by Roboroads** [comment]
@gakkiismywife Please use the [bug report template](https://github.com/Roboroads/laravel-tinker/issues/new?assignees=&labels=bug&template=bug_report.md&title=) if this still needs to be addressed. Thanks!
