### ISSUE TITLE
Issue after updating phpstorm version

### ISSUE THREAD

**Issue by Algeneralo** [Roboroads/laravel-tinker#159]
**Screenshots**
![image](https://user-images.githubusercontent.com/32073999/167585914-745fd8ca-5c2a-428e-840e-286d28284ba9.png)

**Environment (please complete the following information):**
 - IDE & Version: 2022.1
 - PHP Version: 8.1
 - OS: Windows 10
 - Laravel Tinker plugin version : 2.3.3
 - Interpreter Type: Local 
 - Laravel Version: 9.11
 - Tinker version: 2.7

**Comment by SanderCokart** [comment]
same issue here, really threw me off for an hour.

**Comment by Roboroads** [comment]
I seem to not be able to reproduce this issue - and since i'm on vacation till the 28th I do not have the resources to test it on windows, sorry!

**Comment by SanderCokart** [comment]
This worked! Thank you @EgorGruzdev !
