### ISSUE TITLE
Pressing the keyboard shortcut when the output window has focus creates a new console window

### ISSUE THREAD

**Issue by Evertt** [Roboroads/laravel-tinker#16]
**Bug description**
See title.

**To Reproduce**
* Press ctrl+shift+T to open a console window.
* Write some random code, e.g. `echo mt_rand(1, 100);`
* Press ctrl+shift+T to render the output
* Press ctrl+shift+T again

**Expected behavior**
I would expect the code from my console window (which was already open, just not in focus) to be run again.

**What actually happens**
Instead, a new console window is opened.

**Comment by Roboroads** [comment]
You're right. The last executed code feature in 1.1.1 could come in handy with this.

**Comment by Roboroads** [comment]
Closed this by accident
