### ISSUE TITLE
Tinker keeps running in background

### ISSUE THREAD

**Issue by mosbror** [Roboroads/laravel-tinker#162]
**Bug description**
When running a thinker script the process keeps running even after all code has been executed.

**To Reproduce**
Run tinker without exit() or die()

**Expected behavior**
Tinker should exit with message ```*** Execution finished ***``` after all code has been executed.

**Screenshots**
![tinker](https://user-images.githubusercontent.com/10770171/171158107-1d4881ae-92f7-412b-b8b2-f37598cff11a.png)

**Environment (please complete the following information):**
 - IDE & Version: PHPStorm 2020.2.4
 - PHP Version: 8.1
 - OS: macOS 11.6
 - Laravel Tinker plugin version : 2.3.3
 - Interpreter Type: Remote
 - Laravel Version: 8.83.12
 - Tinker version: 2.7.2

**Comment by axcherednikov** [comment]
@Roboroads Same problem.

**Comment by lazer-hybiz** [comment]
same here

**Comment by hailwood** [comment]
Present in 2022.2 EAP

**Comment by rimuutfatih** [comment]
Same. 2022.2 EAP with New UI plugin

**Comment by Roboroads** [comment]
I'm going to look at this one as soon as I fix my IDE

**Comment by Roboroads** [comment]
Fix is ready - will be released in 2.3.4

Workarounded by just adding an exit() to the php code. Psysh is begin a _not nice product_ when working with it like I do.

**Comment by Roboroads** [comment]
That just kills the output entirely, reverting :P
