### ISSUE TITLE
Run Tinker inside a docker container

### ISSUE THREAD

**Issue by bomas13** [Roboroads/laravel-tinker#17]
**Is your feature request related to a problem? Please describe.**
If using docker and having a separate container for the database and app it's may necessary to run tinker from inside of the app container

**Describe the solution you'd like**
provide a small configuration page to set up in which container tinker should run in.

**Describe alternatives you've considered**
none

**Additional context**
none

Greeting,
Thomas

**Comment by Roboroads** [comment]
@bomas13 use the PHP interpreter settings. If you set the PHP interpreter to the app container's PHP it runs in there.

Let me know if this helps 😊

**Comment by bomas13** [comment]
Ah... you're right. It is my fault. I recognized that I run into this issue: https://github.com/Roboroads/laravel-tinker/issues/14

**Comment by Roboroads** [comment]
@bomas13 For now try to set your docker interpreter to do a docker run instead of an exec. I'm not sure yet why #14 happens
