### ISSUE TITLE
Database access results in php_network_getaddresses error

### ISSUE THREAD

**Issue by matthewknill** [Roboroads/laravel-tinker#172]
**Bug description**
Database access does not work resulting in the following error:
```
Illuminate\Database\QueryException with message 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mysql failed: Name or service not known (SQL: select * from `orders` where `orders`.`id` = 2 limit 1)'
```

**To Reproduce**
Run any code that requires access to the database. If the code does not require access to the database, it seems to work fine.
I can also confirm that my application has access to the database and running tinker locally with `sail artisan tinker` also works fine with the database.

The following is the code that I used:
```php
//Tinker away!

use App\Models\Order;

Order::find(2);
```

**Screenshots**
![image](https://user-images.githubusercontent.com/50228686/173805834-8312ede1-971f-4c92-9dd8-44cd81f0a16a.png)

**Environment (please complete the following information):**
 - IDE & Version: IntelliJ IDEA 2022.1.2 (Ultimate Edition)
 - PHP Version: 8.1.7
 - OS: Windows 10
 - Laravel Tinker plugin version: 2.3.4
 - Interpreter Type: Docker (using Laravel Sail)
 - Laravel Version: 8.83
 - Tinker version: 2.7.2

**Comment by Roboroads** [comment]
This usually means that the interpreter you are using not the one is you are developing with. Not a problem with tinker - just that where you run PHP cannot reach your DB from there.

**Comment by matthewknill** [comment]
Thanks for that, when I ran `docker exec -it containername php artisan tinker`, it worked fine. Is that not to be expected?

**Comment by matthewknill** [comment]
It's definitely the correct image and I've tried changing the path mappings to `/var/www/html` and PHP executable to the following to no avail:
```bash
whereis php # run in Laravel sail shell
php: /usr/bin/php8.1 /usr/bin/php /usr/lib/php /etc/php /usr/include/php /usr/share/php
```
![image](https://user-images.githubusercontent.com/50228686/173965772-08fe1b38-84ef-4bf4-ab41-a28e1ec599f1.png)

Your help is much appreciated thanks...

**Comment by Roboroads** [comment]
I'm still 98% sure this is a thing in your setup that's not working. The plugin is not doing anything with your networking. Does a sail command do some extra linking whilst running as just a docker container isn't, maybe?

I could take a gander at it over a screenshare on discord if you want to. If you'd like, message me and we'll figure out a time. Roboroads#1337.

**Comment by matthewknill** [comment]
Thanks, request sent

**Comment by matthewknill** [comment]
Solution was to use `docker-compose.yml` and setting it as `docker-compose exec`:
![image](https://user-images.githubusercontent.com/50228686/174413971-9a12f770-3c44-4ba4-9bd7-bb068aef96bd.png)

I then faced the following issue which, I believe, can be solved by upgrading to the latest PHPStorm version: https://github.com/Roboroads/laravel-tinker/issues/14

**Comment by garbinmarcelo** [comment]
Hello, I'm using OS Win11 with WSL2, in the current project I use Laradock with Laravel 7.

I tried to run the command as shown below, but the error is returned in the output.

![image](https://github.com/Roboroads/laravel-tinker/assets/9335588/0d9cb4f6-5280-4f2c-abef-635b274208c4)

CLI
![image](https://github.com/Roboroads/laravel-tinker/assets/9335588/db1391b6-59f6-4f05-8b52-392d3bae561a)


Do I need to configure anything else in PhpStorm?

**Comment by Roboroads** [comment]
So that means the settings in your .env (or config/database.php ofc.) Are not valid for thst docker container. Make sure that the docker container has a way to connect to the database (make sure they are in the same network?)

I would suggest using docker compose, the setup is a little more user friendly.

**Comment by garbinmarcelo** [comment]
I use Laradock in this project, the settings in the .env file are correct, even because I use migrations and access externally in DBMS normally.
That's why I thought it could have some additional configuration.

Where does Laravel Tinker get the credentials/host to access the database? from the .env file?

**Comment by Roboroads** [comment]
The plugin runs PHP like you configured. So in your case, Tinker runs as if you were to `docker run --rm -it blankedout-workspace:latest php artisan tinker`. You need to be sure to also add all the other settings to be able to connect to your DB container.

I just checked the Laradock docs, and it's using the following compose file for MySQL:

```yaml
   mysql:
      # Redacted unuseful information
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend
```

PHPStorn, using this method, spins up a new docker container. Your new container is probably not in this composes "backend" network - which you need to add to your interpreter settings. The reason your webcontainer is able to connect is because following the compose file, they are in the same network (as your migrations are working) and since port 3306 is exposed to yor hostcomputer, your DBMS is able to connect to localhost:3306.

> Dont just use `--network backend`. Since it's a compose file the name is probablyt a little different. Check which network it is using `docker network list`.

**Comment by quantumwebco** [comment]
In the latest PHPStorm there is no option for "docker-compose exec". When I run ```docker exec -it containername php artisan tinker``` it works fine and my interpreter settings are all correct

<img width="630" alt="image" src="https://github.com/Roboroads/laravel-tinker/assets/12368817/77a53c04-24bc-4e65-b905-433718ba99d3">

**Comment by Roboroads** [comment]
@quantumwebco 
I, using the latest PHPStorm, have the option to choose. 
![image](https://github.com/Roboroads/laravel-tinker/assets/4398301/b16f84a4-243e-438b-8c2c-438edf5dedd6)

You're not using compose btw, just raw docker. Make sure your newly spun up container can reach the mysql instance :)

**Comment by Roboroads** [comment]
@quantumwebco Your interpreter is "Docker", not "Docer compose". 

![image](https://github.com/Roboroads/laravel-tinker/assets/4398301/71a7b639-2f2e-4369-bd20-d4dd616c7835)
(when creating an interpreter)

If you want to keep on using docker, the container needt all the settings it needs to reach the mysql container.

**Comment by quantumwebco** [comment]
Aaah I see, thank you so much!! Just got it working. Might be worth mentioning that you need to choose "Docker for windows - default" as I trued with WSL first but that didn't work. It's my ignorance tho, I just haven't got my head round docker at all yet

**Comment by JohnLeet** [comment]
@Roboroads I had the same issue with the database using docker. But when I changed php to docker-compose Tinker stopped work totally 
Could you help, please?

**Comment by briedis** [comment]
Ok, I just wasted like a few hours on this too.

I have reasons to believe that phpstorm has problems with parsing the docker compose file which is version 3.
I asked chatgpt to convert the file to version 2.4 (just don't forget to back up).

Then I reconfigured the interpreter, server and testing frameworks in phpstorm. Then it started working...

![image](https://github.com/Roboroads/laravel-tinker/assets/500491/b4015646-9999-4813-bd19-d8a68e707cfc)
![image](https://github.com/Roboroads/laravel-tinker/assets/500491/c0059542-d3ba-4f28-9c10-eb97d9b99177)
![image](https://github.com/Roboroads/laravel-tinker/assets/500491/914ab26b-6cb4-41d0-85a7-52139230b876)
![image](https://github.com/Roboroads/laravel-tinker/assets/500491/a266bb07-8ad8-4e41-9a48-cf4e4d3d14f3)

**Comment by Roboroads** [comment]
> I have reasons to believe that phpstorm has problems with parsing the docker compose file which is version 3. I asked chatgpt to convert the file to version 2.4 (just don't forget to back up).

That should not be the case.. Compose is just a way of running docker..
