### ISSUE TITLE
PHP Fatal error:  Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP?

### ISSUE THREAD

**Issue by guiireal** [Roboroads/laravel-tinker#173]
What's happening?

I created a new Laravel project and went to test tinker, this appeared

Laravel Version: 9.19.0
PHP Version: 8.1.3
PhpStorm 2022.1.2

![image](https://user-images.githubusercontent.com/13739343/177189847-dd166505-ea1b-45b2-8c44-509fa5ea6045.png)

**Comment by guiireal** [comment]
`PHP Fatal error:  Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP? in D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
Stack trace:
#0 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#2 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(791): file_exists('hoa://Library/T...')
#3 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(811): Psy\Readline\Hoa\ConsoleTput::getTerminfo()
#4 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Userland.php(43): Psy\Readline\Hoa\ConsoleTput::isSupported()
#5 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Configuration.php(822): Psy\Readline\Userland::isSupported()
#6 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Configuration.php(794): Psy\Configuration->getReadlineClass()
#7 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Shell.php(92): Psy\Configuration->getReadline()
#8 Command line code(39): Psy\Shell->__construct(Object(Psy\Configuration))
#9 {main}
  thrown in D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php on line 791

   Symfony\Component\ErrorHandler\Error\FatalError 

  Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP? in D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
Stack trace:
#0 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#2 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(791): file_exists('hoa://Library/T...')
#3 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(811): Psy\Readline\Hoa\ConsoleTput::getTerminfo()
#4 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Userland.php(43): Psy\Readline\Hoa\ConsoleTput::isSupported()
#5 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Configuration.php(822): Psy\Readline\Userland::isSupported()
#6 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Configuration.php(794): Psy\Configuration->getReadlineClass()
#7 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Shell.php(92): Psy\Configuration->getReadline()
#8 Command line code(39): Psy\Shell->__construct(Object(Psy\Configuration))
#9 {main}
  thrown

  at D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
    787▕         $fileAlpha = $term[0].\DIRECTORY_SEPARATOR.$term;
    788▕         $pathname = null;
    789▕ 
    790▕         foreach ($paths as $path) {
  ➜ 791▕             if (\file_exists($_ = $path.\DIRECTORY_SEPARATOR.$fileHexa) ||
    792▕                 \file_exists($_ = $path.\DIRECTORY_SEPARATOR.$fileAlpha)) {
    793▕                 $pathname = $_;
    794▕ 
    795▕                 break;


   Whoops\Exception\ErrorException 

  Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP? in D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
Stack trace:
#0 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#2 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(791): file_exists('hoa://Library/T...')
#3 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(811): Psy\Readline\Hoa\ConsoleTput::getTerminfo()
#4 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Userland.php(43): Psy\Readline\Hoa\ConsoleTput::isSupported()
#5 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Configuration.php(822): Psy\Readline\Userland::isSupported()
#6 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Configuration.php(794): Psy\Configuration->getReadlineClass()
#7 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Shell.php(92): Psy\Configuration->getReadline()
#8 Command line code(39): Psy\Shell->__construct(Object(Psy\Configuration))
#9 {main}
  thrown

  at D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
    787▕         $fileAlpha = $term[0].\DIRECTORY_SEPARATOR.$term;
    788▕         $pathname = null;
    789▕ 
    790▕         foreach ($paths as $path) {
  ➜ 791▕             if (\file_exists($_ = $path.\DIRECTORY_SEPARATOR.$fileHexa) ||
    792▕                 \file_exists($_ = $path.\DIRECTORY_SEPARATOR.$fileAlpha)) {
    793▕                 $pathname = $_;
    794▕ 
    795▕                 break;

  1   D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\filp\whoops\src\Whoops\Run.php:486
      Whoops\Run::handleError("Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP? in D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
Stack trace:
#0 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#2 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(791): file_exists('hoa://Library/T...')
#3 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa...", "D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php")

  2   [internal]:0
      Whoops\Run::handleShutdown()

*** Execution finished *** `

**Comment by guiireal** [comment]
```
PHP Fatal error:  Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP? in D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
Stack trace:
#0 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#2 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(791): file_exists('hoa://Library/T...')
#3 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(811): Psy\Readline\Hoa\ConsoleTput::getTerminfo()
#4 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Userland.php(43): Psy\Readline\Hoa\ConsoleTput::isSupported()
#5 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Configuration.php(822): Psy\Readline\Userland::isSupported()
#6 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Configuration.php(794): Psy\Configuration->getReadlineClass()
#7 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Shell.php(92): Psy\Configuration->getReadline()
#8 Command line code(39): Psy\Shell->__construct(Object(Psy\Configuration))
#9 {main}
  thrown in D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php on line 791

   Symfony\Component\ErrorHandler\Error\FatalError 

  Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP? in D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
Stack trace:
#0 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#2 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(791): file_exists('hoa://Library/T...')
#3 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(811): Psy\Readline\Hoa\ConsoleTput::getTerminfo()
#4 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Userland.php(43): Psy\Readline\Hoa\ConsoleTput::isSupported()
#5 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Configuration.php(822): Psy\Readline\Userland::isSupported()
#6 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Configuration.php(794): Psy\Configuration->getReadlineClass()
#7 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Shell.php(92): Psy\Configuration->getReadline()
#8 Command line code(39): Psy\Shell->__construct(Object(Psy\Configuration))
#9 {main}
  thrown

  at D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
    787▕         $fileAlpha = $term[0].\DIRECTORY_SEPARATOR.$term;
    788▕         $pathname = null;
    789▕ 
    790▕         foreach ($paths as $path) {
  ➜ 791▕             if (\file_exists($_ = $path.\DIRECTORY_SEPARATOR.$fileHexa) ||
    792▕                 \file_exists($_ = $path.\DIRECTORY_SEPARATOR.$fileAlpha)) {
    793▕                 $pathname = $_;
    794▕ 
    795▕                 break;


   Whoops\Exception\ErrorException 

  Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP? in D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
Stack trace:
#0 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#2 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(791): file_exists('hoa://Library/T...')
#3 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(811): Psy\Readline\Hoa\ConsoleTput::getTerminfo()
#4 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Userland.php(43): Psy\Readline\Hoa\ConsoleTput::isSupported()
#5 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Configuration.php(822): Psy\Readline\Userland::isSupported()
#6 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Configuration.php(794): Psy\Configuration->getReadlineClass()
#7 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Shell.php(92): Psy\Configuration->getReadline()
#8 Command line code(39): Psy\Shell->__construct(Object(Psy\Configuration))
#9 {main}
  thrown

  at D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
    787▕         $fileAlpha = $term[0].\DIRECTORY_SEPARATOR.$term;
    788▕         $pathname = null;
    789▕ 
    790▕         foreach ($paths as $path) {
  ➜ 791▕             if (\file_exists($_ = $path.\DIRECTORY_SEPARATOR.$fileHexa) ||
    792▕                 \file_exists($_ = $path.\DIRECTORY_SEPARATOR.$fileAlpha)) {
    793▕                 $pathname = $_;
    794▕ 
    795▕                 break;

  1   D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\filp\whoops\src\Whoops\Run.php:486
      Whoops\Run::handleError("Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP? in D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
Stack trace:
#0 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'file_exists(): ...', 'D:\\Gui\\Tecnolog...', 791)
#2 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(791): file_exists('hoa://Library/T...')
#3 D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa...", "D:\Gui\Tecnologia_da_Informacao\Projetos_Atuais\centro-britanico\services\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php")

  2   [internal]:0
      Whoops\Run::handleShutdown()

*** Execution finished ***
                                
```

**Comment by GuilhermeFerro** [comment]
Same problem in my configuration:
```
Laravel Version: 8.83
PHP Version: 8.0.9
PhpStorm 2021.1.3
```

```php
PHP Fatal error:  Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP? in C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_exists(): ...', 'C:\\Users\\Gui\\Ph...', 791)
#1 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(791): file_exists('hoa://Library/T...')
#2 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(811): Psy\Readline\Hoa\ConsoleTput::getTerminfo()
#3 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Userland.php(43): Psy\Readline\Hoa\ConsoleTput::isSupported()
#4 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Configuration.php(822): Psy\Readline\Userland::isSupported()
#5 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Configuration.php(794): Psy\Configuration->getReadlineClass()
#6 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Shell.php(92): Psy\Configuration->getReadline()
#7 Command line code(34): Psy\Shell->__construct(Object(Psy\Configuration))
#8 {main}
  thrown in C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php on line 791

   Symfony\Component\ErrorHandler\Error\FatalError 

  Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP? in C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_exists(): ...', 'C:\\Users\\Gui\\Ph...', 791)
#1 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(791): file_exists('hoa://Library/T...')
#2 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(811): Psy\Readline\Hoa\ConsoleTput::getTerminfo()
#3 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Userland.php(43): Psy\Readline\Hoa\ConsoleTput::isSupported()
#4 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Configuration.php(822): Psy\Readline\Userland::isSupported()
#5 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Configuration.php(794): Psy\Configuration->getReadlineClass()
#6 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Shell.php(92): Psy\Configuration->getReadline()
#7 Command line code(34): Psy\Shell->__construct(Object(Psy\Configuration))
#8 {main}
  thrown

  at C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
    787▕         $fileAlpha = $term[0].\DIRECTORY_SEPARATOR.$term;
    788▕         $pathname = null;
    789▕ 
    790▕         foreach ($paths as $path) {
  ➜ 791▕             if (\file_exists($_ = $path.\DIRECTORY_SEPARATOR.$fileHexa) ||
    792▕                 \file_exists($_ = $path.\DIRECTORY_SEPARATOR.$fileAlpha)) {
    793▕                 $pathname = $_;
    794▕ 
    795▕                 break;


   Whoops\Exception\ErrorException 

  Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP? in C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_exists(): ...', 'C:\\Users\\Gui\\Ph...', 791)
#1 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(791): file_exists('hoa://Library/T...')
#2 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(811): Psy\Readline\Hoa\ConsoleTput::getTerminfo()
#3 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Userland.php(43): Psy\Readline\Hoa\ConsoleTput::isSupported()
#4 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Configuration.php(822): Psy\Readline\Userland::isSupported()
#5 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Configuration.php(794): Psy\Configuration->getReadlineClass()
#6 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Shell.php(92): Psy\Configuration->getReadline()
#7 Command line code(34): Psy\Shell->__construct(Object(Psy\Configuration))
#8 {main}
  thrown

  at C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
    787▕         $fileAlpha = $term[0].\DIRECTORY_SEPARATOR.$term;
    788▕         $pathname = null;
    789▕ 
    790▕         foreach ($paths as $path) {
  ➜ 791▕             if (\file_exists($_ = $path.\DIRECTORY_SEPARATOR.$fileHexa) ||
    792▕                 \file_exists($_ = $path.\DIRECTORY_SEPARATOR.$fileAlpha)) {
    793▕                 $pathname = $_;
    794▕ 
    795▕                 break;

  1   C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\filp\whoops\src\Whoops\Run.php:486
      Whoops\Run::handleError("Uncaught ErrorException: file_exists(): Unable to find the wrapper "hoa" - did you forget to enable it when you configured PHP? in C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php:791
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_exists(): ...', 'C:\\Users\\Gui\\Ph...', 791)
#1 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(791): file_exists('hoa://Library/T...')
#2 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php(811): Psy\Readline\Hoa\ConsoleTput::getTerminfo()
#3 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Userland.php(43): Psy\Readline\Hoa\ConsoleTput::isSupported()
#4 C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Configurati...", "C:\Users\Gui\PhpstormProjects\GSFERRO\walter\LEITOR PDF\leitor-pdf\vendor\psy\psysh\src\Readline\Hoa\ConsoleTput.php")

  2   [internal]:0
      Whoops\Run::handleShutdown()
*** Execution finished ***
```

**Comment by Sohbet02** [comment]
ConsoleTput.php file, for me it wasn't opening tinker. Fixed it with commenting and adding the location of the terms file on my local windows machine:
![image](https://user-images.githubusercontent.com/64475819/178056193-ec9d2a78-f972-476c-b856-afe2685ede0d.png)

**Comment by leandrodiogenes** [comment]
anyone else with a better solution, i'll not modify my vendor folder.

**Comment by Roboroads** [comment]
Excuse me for the lack of response - I'm not dead, covid happened :(

I'm going to look at this soon, currently in the process of upgrading another project.

**Comment by Roboroads** [comment]
I don't create the bug templates for nothing. I tested this with: 

- Laravel version: 8.83 / PHP Version: 8.0.9 / PhpStorm 2021.1.3
- Laravel Version: 9.19.0 / PHP Version: 8.1.3 / PhpStorm 2022.1.2

Both instances working just fine here. So, it's not a bugh to do with these 3 environment versions. Please add *all* of them. Here is a reminder:

 - IDE & Version: [e.g. PHPStorm 2020.2.1]
 - PHP Version: [e.g. 7.4] (Find out with `php -v`)
 - OS: [e.g. Windows 10, macOS 10.15, Ubuntu 20.04]
 - Laravel Tinker plugin version : [e.g. 1.1.1]
 - Interpreter Type: (One of the following: Local / Remote / Docker / Docker-compose)
 - Laravel Version: [e.g. 7.3.0] (Find out with `composer show laravel/framework`)
 - Tinker version: [e.g. 2.3.0] (Find out with `composer show laravel/tinker`)

**Comment by leandrodiogenes** [comment]
Hey @Roboroads seems to be an psy/psysh issue.
Look at that [https://github.com/bobthecow/psysh/issues/722](url)

**Comment by leandrodiogenes** [comment]
I solve my problem dowgrading psy/psysh to "0.11.2"

**Comment by Roboroads** [comment]
I forgot this was the issue, yes, thanks.

Workaround available in https://github.com/Roboroads/laravel-tinker/issues/164#issuecomment-1143595797
