### ISSUE TITLE
Execution exits too early

### ISSUE THREAD

**Issue by leandrodiogenes** [Roboroads/laravel-tinker#178]
**Bug description**
I dont know how to explain beter, but sometimes the result shows, sometimes not.

**To Reproduce**
Just executing any script.

**Screenshots**
![image](https://user-images.githubusercontent.com/2463299/181636728-6d26e5c3-c401-4947-a754-7f126b2fd486.png)
![image](https://user-images.githubusercontent.com/2463299/181636736-0337326c-c6ad-4cea-b219-66951b910eb4.png)
![image](https://user-images.githubusercontent.com/2463299/181636701-81edf0df-81d3-4f75-9e52-86de110a2642.png)

Another exemple:
![image](https://user-images.githubusercontent.com/2463299/181638144-76cef772-da0c-472c-bcf8-f68c21a0459f.png)
![image](https://user-images.githubusercontent.com/2463299/181638186-c362c700-d268-48d9-b568-382b29d95f05.png)

**Expected results**
![image](https://user-images.githubusercontent.com/2463299/181638274-ac7cbf79-4a9d-4adb-ba90-953e2abbac87.png)
![image](https://user-images.githubusercontent.com/2463299/181638449-ca33cbfe-a28c-40dc-a8b0-d66d43d36434.png)

**Environment:**
 - IDE & Version: PHPStorm 2021.3.2 Build #PS-213.6777.58
 - PHP Version: 7.4.30
 - OS: Windows 10
 - Laravel Tinker plugin version : 2.3.4
 - Interpreter Type: Local
 - Laravel Version: 8.83.20
 - Tinker version: 2.7.2

**Comment by Roboroads** [comment]
I already (tried to fix it) [https://github.com/Roboroads/laravel-tinker/commit/061cd6eab0dbe9dfef2e1c19631594c0a11b0884] but i do not think this is the solution. This week be fixed soon.

**Comment by leandrodiogenes** [comment]
thanks @Roboroads

**Comment by Roboroads** [comment]
2.4.0 will be available this week after JB accepts it, which includes this issue.
