### ISSUE TITLE
Question: is there a hotkey for "running" the code?

### ISSUE THREAD

**Issue by michabbb** [Roboroads/laravel-tinker#179]
i am asking, because the green arrow we are used to see in the jetbrains editor is not the same "run" tinker is doing.
so the IDE hotkey for "run this code" is (in my case): CTRL+SHIFT+F10 - but it´s not the same kind of "run" that happens,
when pressing this button:

![image](https://user-images.githubusercontent.com/3524595/181934824-7c79a569-d264-4f59-ac60-85266f45d7f9.png)

so if there would be a separate hotkey, it would be nice.

**Comment by michabbb** [comment]
![image](https://user-images.githubusercontent.com/3524595/181934963-4feec9b6-8625-4fdf-9dcf-19bcd5f1b46d.png)

ups... found it 😏

**Comment by Roboroads** [comment]
Yes, every action has customizable hotkeys :D
