### ISSUE TITLE
LARAVEL_START constant is undefined

### ISSUE THREAD

**Issue by daniser** [Roboroads/laravel-tinker#18]
**Bug description**
Plugin can't see LARAVEL_START constant declared in "artisan" script.

**To Reproduce**
`<?php echo LARAVEL_START;` in tinker console.

**Expected behavior**
LARAVEL_START is predefined Laravel constant and should be visible by the plugin console (it works in artisan tinker BTW).

**Environment**
 - IDE & Version: PHPStorm 2020.2.1
 - PHP Version: 7.4.5
 - Interpreter Type: Local
 - Laravel Version: 7.28.0
 - Tinker version: 2.4.2

**Comment by Roboroads** [comment]
I'm not running your console through the exact `php artisan tinker` command, just using the way it processes input. Where do you need this constant for?

**Comment by daniser** [comment]
It is used in my project to measure script execution time. It's large project with tons of legacy code. Is there a way to tinker (sic!) with this wrapper script to add custom bootstrap code to it?

**Comment by Roboroads** [comment]
I'll add the constant in the following version - for now you could prepend your script to work around the problem.

```php
<?php
define('LARAVEL_START', microtime(true));
//Tinker code
```

**Comment by daniser** [comment]
> I'll add the constant in the following version - for now you could prepend your script to work around the problem.
> 
> ```
> <?php
> define('LARAVEL_START', microtime(true));
> //Tinker code
> ```
Just FYI: this doesn't help because, as I said, this constant is used inside service provider that boots before tinker script execution:
![tinker](https://user-images.githubusercontent.com/5169543/92712058-72b00a80-f359-11ea-90d2-83d1730b1e35.png)

But it's no problem, I'll just wait for the next version. Thank you.

**Comment by Roboroads** [comment]
Ah yea, gotcha. It's queued for 1.1.2 ✌️

**Comment by Roboroads** [comment]
@daniser This fix got released this week, is it now fixed for you?

**Comment by daniser** [comment]
> @daniser This fix got released this week, is it now fixed for you?

Yeah, already checked it out, works great. Thank you!

P.S. Some little annoying bugs remained though, when trying to execute empty shell:
`<?php 1;` gives me output:
```
// Laravel Tinker started at 2020-09-20 21:46:56
=> 1
*** Execution finished ***
```
... looks good, but this:
`<?php;` doubles notification:
```
// Laravel Tinker started at 2020-09-20 21:51:04
*** Execution finished ***
*** Execution finished ***
```
... and when I omit semicolon entirely like that:
`<?php` it gives me this error:
```
// Laravel Tinker started at 2020-09-20 21:53:14
=> null
 PHP Warning:  array_filter() expects parameter 1 to be array, null given in D:/OSPanel/domains/ttb/lib/lozovsky/vendor/psy/psysh/src/Shell.php on line 1012 
 PHP Warning:  implode(): Invalid arguments passed in D:/OSPanel/domains/ttb/lib/lozovsky/vendor/psy/psysh/src/Shell.php on line 1014 
*** Execution finished ***
```
Not that it's huge problem (who in their sane mind installs Tinker console to execute nothing, lol :), but I still think it'll be good to add some consistency in output in that case.

**Comment by Roboroads** [comment]
Adding <?php is not even necessary, you can run php code without it, it's just there to make the ide know that you are in php code. double execution finish message is probably because you press the shortcut twice. That is indeed a bug I wanted to fix but forgot.
