### ISSUE TITLE
tinker not work properly with phpstorm 2022

### ISSUE THREAD

**Issue by mahdi-salah** [Roboroads/laravel-tinker#180]
**Bug description**

the tinker not work properly with all versions of phpstorm 2022

and this video explain the problem:

https://drive.google.com/file/d/1_jObub4HmPGwpfXe4usioeUBL29x8dZH/view?usp=sharing

BUT its working well with phpstorm 2021

thanks for amazing tinker :)

**Comment by Roboroads** [comment]
Same bug as #178

**Comment by mahdi-salah** [comment]
> Same bug as #178

thank you Roboroads so much .. But how where can I find this part of code to make edit .. because I installed the plugin and I don't know how to deal with it to make changes .. Thank you in advance :)

**Comment by Roboroads** [comment]
@mahdi-salah I still have to release the fix. I will see to it today.

**Comment by Roboroads** [comment]
2.4.0 will be available this week after JB accepts it, which includes this issue.

**Comment by mahdi-salah** [comment]
> 2.4.0 will be available this week after JB accepts it, which includes this issue.

Thank you SO much for your efforts Roboroads :)
