### ISSUE TITLE
Changing the font size in the console output

### ISSUE THREAD

**Issue by iron-viper** [Roboroads/laravel-tinker#188]
**Is your feature request related to a problem? Please describe.**
I am working on a laptop in PhpStorm and there is a very small font in the plugin output.

**Describe the solution you'd like**
It would be nice to be able to adjust the font size for the plugin.

**Describe alternatives you've considered**
It may just be enough to increase the font size in the output text.

**Additional context**
Thanks a lot for the plugin.

**Comment by lazer-hybiz** [comment]
https://github.com/Roboroads/laravel-tinker/issues/22
