### ISSUE TITLE
Output window requires restart to follow IDE style

### ISSUE THREAD

**Issue by Roboroads** [Roboroads/laravel-tinker#19]
**Bug description**
See title

**To Reproduce**
Install plugin, run tinker before restarting

**Expected behavior**
Should have the IDE style inheritted

**Comment by ricardoaponte** [comment]
I am using the Darcula theme and the color combination for the fonts cannot be changed. Attached is an example of how it looks.

![image](https://user-images.githubusercontent.com/406591/93269198-8d7ce780-f77c-11ea-833e-5b8516a0fd75.png)

**Comment by Roboroads** [comment]
@ricardoaponte I'm aware - this is why this issue is here. Thanks for helping tho :)

**Comment by Roboroads** [comment]
Fixed in https://github.com/Roboroads/laravel-tinker/commit/65a51528dff478f31aeb73976aa1fa5dcc86493c
