### ISSUE TITLE
Bug if project root is not laravel root

### ISSUE THREAD

**Issue by bobisdacool1** [Roboroads/laravel-tinker#190]
**Bug description**
I've got project root. The vendor directory is located at the project root, `./ProjectRoot/vendor`. My laravel directory is in the projects directory, `./ProjectRoot/projects/laravel-directory`. When I try to run the laravel tinker script, I get fatal error: `Fatal error: Uncaught Error: Failed opening required './ProjectRoot/bootstrap/app.php'`.
I tried changing laravel tinker project directory to the `./ProjectRoot/projects/laravel-directory`, but still got same error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/49680047/185076281-efd72dd1-e705-4704-a5a8-dad5fe63270a.png)

**Environment (please complete the following information):**
 - IDE & Version: PHPStorm 2022.2
 - PHP Version: 8.1.15
 - OS: Windows 10
 - Laravel Tinker plugin version : 2.4.0
 - Interpreter Type: local
 - Laravel Version: v8.83.15
   Tinker version: v2.7.2
   
   
P.S. Thank you very much for making such a good plugin, it has greatly increased the speed of my development

**Comment by bobisdacool1** [comment]
> 

I have already created a pull request for this bug

**Comment by Roboroads** [comment]
Ready for next release!
