### ISSUE TITLE
Any chance of tinker-over-ssh support?

### ISSUE THREAD

**Issue by treii28** [Roboroads/laravel-tinker#201]
**Is your feature request related to a problem? Please describe.**
Support for connecting to a remote site before running tinker so code can be run directly in a staging or production environment for testing.

**Describe the solution you'd like**
Great use-case just popped up for me. I have an API I'm developing for that requires specifying your website's url as part of their application process then only allows communications (as part of the security) from that url. Short of creating a second test site on the 'live/production' server, this means any testing of the actual communication that isn't mocked has to be run from a server running on the live environment.

**Describe alternatives you've considered**
Using an alternate port on my production server with a whitelisted block-all-only-allow rule seems to work but my current implementation is small, so I was able to accommodate that.

But if I want to run tests of code changes in tinker, anything that actually triggers a restful response won't work from a 'localhost' url as the remote server will deny it with the default 'callback url does not match your app's registered FQDN' message.

My only solution for the time being is to use an ssh terminal window, connect to the remote host and then run tinker manually which defeats the purpose of having the Tinker plugin installed. (I can also do that locall)

**Comment by Roboroads** [comment]
I don;'t see why you can't do it right now. Just connect a remore interpreter :)

![image](https://user-images.githubusercontent.com/4398301/197539774-0eed9e3d-bc76-4c5a-adaf-8d7c7ebd0632.png)

![image](https://user-images.githubusercontent.com/4398301/197539901-745ff6c8-3c92-46f7-a887-0192abd521b8.png)

![image](https://user-images.githubusercontent.com/4398301/197539972-3229c8a3-7a72-42f6-aaa8-eeed238fce80.png)
