### ISSUE TITLE
Laravel 9 Tinker Plugin Bug. adds: <whisper>= </whisper> to output.

### ISSUE THREAD

**Issue by SanderCokart** [Roboroads/laravel-tinker#212]
# Bug description
At the start of a fresh install of laravel 9 the plugin prepends any output with `<whisper>= </whisper>`.

# To Reproduce
* In mysql / mariadb database shell
`create database test;`

* In console
`laravel new test`
`migrate:fresh`

* In phpstorm
open tinker plugin.
enter:
```php
<?php
User::factory()->create();
```

* output
```php
// Laravel Tinker started at 2022-12-05 02:38:27
                                                            
<whisper>= </whisper>App\Models\User {#3188
    name: "Dr. Carey Klocko",
    email: "rbednar@example.net",
    email_verified_at: "2022-12-05 01:38:27",
    #password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    #remember_token: "YluhFBHZYU",
    updated_at: "2022-12-05 01:38:27",
    created_at: "2022-12-05 01:38:27",
    id: 3,
  }


*** Execution finished ***
                                
                            
                        
```

# Expected behavior
* expected output
```php
// Laravel Tinker started at 2022-12-05 02:38:27
                                                            
App\Models\User {#3188
    name: "Dr. Carey Klocko",
    email: "rbednar@example.net",
    email_verified_at: "2022-12-05 01:38:27",
    #password: "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    #remember_token: "YluhFBHZYU",
    updated_at: "2022-12-05 01:38:27",
    created_at: "2022-12-05 01:38:27",
    id: 3,
  }


*** Execution finished ***
                                
                            
                        
```

# Screenshots
![image](https://user-images.githubusercontent.com/45256817/205530890-f284f316-aa99-4839-bb09-92beca6e84eb.png)

# Environment
 - IDE & Version: 2022.2.4
 - PHP Version: 8.1.9
 - OS: Windows 10
 - Laravel Tinker plugin version : 2.4.0
 - Interpreter Type: Local
 - Laravel Version: 9.42.2
 - Tinker version: 2.7.3

**Comment by pajkho** [comment]
Have the same issue with Laravel 8.

**Comment by Roboroads** [comment]
Did tinker or physh have an update..? Let's see.

**Comment by Roboroads** [comment]
So there is this theme update from Psysh. Let's see if it helps by reverting to the old layout

**Comment by Roboroads** [comment]
@pajkho  @SanderCokart 

[Laravel Tinker-2.4.0+1.zip](https://github.com/Roboroads/laravel-tinker/files/10212544/Laravel.Tinker-2.4.0%2B1.zip)
Does this build fix your problem? It's based on [this branches changes](https://github.com/Roboroads/laravel-tinker/tree/fix/psysh_update)

**Comment by SanderCokart** [comment]
when manually adding psy/psych to the composer.json require-dev
```bash

$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Downgrading psy/psysh (v0.11.9 => v0.11.8)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downgrading psy/psysh (v0.11.9 => v0.11.8): Extracting archive
Generating optimized autoload files
```

When removing it and then:
```bash
composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading psy/psysh (v0.11.8 => v0.11.9)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Upgrading psy/psysh (v0.11.8 => v0.11.9): Extracting archive
Generating optimized autoload files
```

However with it not being in composer.json even `composer show psy/psych --all` says the package is not found.

**Comment by Roboroads** [comment]
Manually installing 0.11.8?

**Comment by SanderCokart** [comment]
Yes, a manual install of 0.11.9 breaks it and shows <whisper> again.

**Comment by Roboroads** [comment]
Alright, so it is the theme update op psysh.

Command is `composer show -a psy/psysh` btw, just figured it out xD

**Comment by SanderCokart** [comment]
Also nevermind the console outputs of the removing and adding manually. False info, read my terminal wrong,

**Comment by SanderCokart** [comment]
Right ok so with it NOT in composer.json
```
composer show -a psy/psysh | grep versions
versions : 0.11.x-dev, * v0.11.9, v0.11.8, v0.11.7, v0.11.6, v0.11.5, v0.11.4, v0.11.3, v0.11.2, v0.11.1, v0.11.0, 0.10.x-dev, v0.10.12, v0.10.11, v0.10.10, v0.10.9, v0.10.8, v0.10.7, v0.10.6, v0.10.5, v0.10.4, v0.10.3, v0.10.2, v
0.10.0, v0.9.12, v0.9.11, v0.9.9, v0.9.8, v0.9.7, v0.9.6, v0.9.5, v0.9.4, v0.9.3, v0.9.2, v0.9.1, v0.9.0, v0.8.18, v0.8.17, v0.8.16, v0.8.15, v0.8.14, v0.8.13, v0.8.12, v0.8.11, v0.8.10, v0.8.9, v0.8.8, v0.8.7, v0.8.6, v0.8.5, v0.
8.4, v0.8.3, v0.8.2, v0.8.1, v0.8.0, v0.7.2, v0.7.1, v0.7.0, v0.6.1, v0.6.0, v0.5.2, v0.5.1, v0.5.0, v0.4.4, v0.4.3, v0.4.2, v0.4.1, v0.4.0, v0.3.5, v0.3.4, v0.3.3, v0.3.2, v0.3.1, v0.3.0, v0.2.1, v0.2.0, v0.1.12, v0.1.11, v0.1.10, v0.1.9, v0.1.8, v0.1.7, v0.1.6, v0.1.5, v0.1.4, v0.1.3, v0.1.2, v0.1.1, v0.1.0, dev-main, dev-better-throwable-support, dev-static-analysis, dev-develop
```

**Comment by Roboroads** [comment]
The one with the star, 0.11.9

So, i'm fairly certain the new theme system breaks output, this is enought info for me to fix it <3

**Comment by SanderCokart** [comment]
So fun how anytime psy/psych updates you have work to do <3

**Comment by SanderCokart** [comment]
You need like a CI something that listens for updates on the package and then auto run tests. I don't know if such things exist but I am assuming it does.

**Comment by Roboroads** [comment]
This isn't the first time a psysh update breaks the plugin, but it's ultimately my fault for not yet having figured out how to get the ansi-colored output and just transforming that to HTML. Currently I'm doing [all kinds of hocus-pocus](https://github.com/Roboroads/laravel-tinker/blob/main/src/main/kotlin/nl/deschepers/laraveltinker/toolwindow/TinkerOutputToolwindow.kt#L147-L184) to get colors in the output which is, well, not ideal :)

**Comment by SanderCokart** [comment]
That looks like the most "fun" functions and fun regex expressions. 
Who knows maybe copilot can figure something out xD

**Comment by SanderCokart** [comment]
Still thanks for making this plugin in the first place, its awesome having code hinting for Tinker!

**Comment by Roboroads** [comment]
Actually, I might have just found ansi colors

**Comment by Roboroads** [comment]
Aight. I build an ansi color parser. The hocuspocus of regex is gone. Huzza!

Also, this is fixed :)

**Comment by SanderCokart** [comment]
So whens the release? :D

**Comment by Roboroads** [comment]
https://github.com/Roboroads/laravel-tinker/issues/217

**Comment by Roboroads** [comment]
Version 2.5.0 is underway, pending JetBrains verification :)
