### ISSUE TITLE
[BUG] Code don't run, output empty

### ISSUE THREAD

**Issue by DanielSpravtsev** [Roboroads/laravel-tinker#215]
**Bug description**
Few weeks ago everything was fine, then Tinker start adding: whisper= /whisper  to output, like described here [issues-212](https://github.com/Roboroads/laravel-tinker/issues/212) and now there is only  *** Execution finished *** note without execution
                              

**To Reproduce**
What did you do to encounter the bug?
Just not working in any project. Laravel8-9, PHP 8.1.13  from brew

**Screenshots**
https://snipboard.io/MwU0yV.jpg

**Environment (please complete the following information):**
 - IDE & Version: PHPStorm 2022.2.2 - 2022.2.4
 - PHP Version: PHP 8.1.13 
 - OS: MacOS 11.2.3
 - Laravel Tinker plugin version : 2.4.0
 - Interpreter Type: Local
 - Laravel Version: 9.38
 - Tinker version: 2.7

**Comment by Roboroads** [comment]
Psysh had a theme update and might be interfering with how the plugin parses output. I should add Psysh version to the bug report thing :)

I hope I fix this by setting the theme to classic. :crossed_fingers:

**Comment by Roboroads** [comment]
@DanielSpravtsev 

[Laravel Tinker-2.4.0+1.zip](https://github.com/Roboroads/laravel-tinker/files/10212544/Laravel.Tinker-2.4.0%2B1.zip)
Does this build fix your problem?

**Comment by Roboroads** [comment]
Version 2.5.0 is underway, pending JetBrains verification :) Let me know if it fixes your issues.

**Comment by Roboroads** [comment]
> I really prefer using in-house code runner rather standalone app, like Tikerwell and etc

That's awesome to hear! Concider [leaving a review](https://plugins.jetbrains.com/plugin/14957-laravel-tinker) or sharing <3

**Comment by DanielSpravtsev** [comment]
@Roboroads This bug happened again. Same description as before

**Environment (please complete the following information):**
IDE & Version: PHPStorm 2022.2.4
PHP Version: PHP 8.2
OS: MacOS 11.2.3
Laravel Tinker plugin version : 2.5.2
Interpreter Type: Local
Laravel Version: 9.52
Tinker version: 2.8.1
