### ISSUE TITLE
[Bug]: Uncaught Error Class App\Models\User not found

### ISSUE THREAD

**Issue by christoferd** [Roboroads/laravel-tinker#219]
### Short bug description

When I run tinker with a simple script it displays an error that a model does not exist

### Extended bug description

The script works fine in command line php artisan tinker.

### How to reproduce?

1. In PHPStorm 2022.3, run tinker, add simple script:
```php
<?php
//Tinker away!
use App\Models\User;
echo User::all();
```
2. Right-click, click "Run 'LaravelTinkerConsole'... " in the context menu.
3. Notice this error appears in the console box:
```
C:\xampp71\php818\php.exe C:\Users\chris\AppData\Roaming\JetBrains\PhpStorm2022.3\laravel-tinker\LaravelTinkerConsole.php
PHP Fatal error:  Uncaught Error: Class "App\Models\User" not found in C:\Users\chris\AppData\Roaming\JetBrains\PhpStorm2021.2\laravel-tinker\LaravelTinkerConsole.php:6
Stack trace:
#0 {main}
  thrown in C:\Users\chris\AppData\Roaming\JetBrains\PhpStorm2022.3\laravel-tinker\LaravelTinkerConsole.php on line 6

Process finished with exit code 255
```

### Expected behavior

I'd expect to see the same as what I see when running Tinker via the CLI.

### Screenshots

[Screenshot Link](https://www.dropbox.com/s/v5v9lyshnvy0qio/Screenshot-2022-12-14-PHPStorm_Tinker_Console.png?dl=0)

![Screenshot-2022-12-14-PHPStorm_Tinker_Console](https://user-images.githubusercontent.com/1835883/207608524-2e5ac148-451f-4250-8b72-351445660b39.png)

### IDE & Version

PhpStorm 2022.3

### PHP Version

8.1.8

### OS and version

Windows 11

### Laravel Tinker plugin version

2.5.0

### Interpreter type

{"label"=>"Local"}

### Laravel Version

9.37.0

### Tinker version

v2.7.2

### Psysh version

v0.11.8

### Additional Context

I just installed the plugin and was testing it.

**Comment by Roboroads** [comment]
Thanks! I'm looking into it ^^

**Comment by Roboroads** [comment]
So, first, I see that the script is not running through my plugin.

> Right-click, click "Run 'LaravelTinkerConsole'... " in the context menu.

This doesn't work - PHPStorm runs the file with his own interpreter. Please use the tinker smart action (ctrl+shift+T) or Tools > Laravel Tinker > Run tinker console (or "Smart action: Run tinker console" - does the same) 

The bug here is that the context menu item should not be there :)

**Comment by Roboroads** [comment]
Closing in favor of #220

**Comment by christoferd** [comment]
Awesome! It's working. Yes, the context menu had me going in the wrong direction.
Only difference is that I see a Tinker icon instead of Play, better. 
? Are these simple instructions on github readme?

**Working :-)**
![2022-12-19 09_30_43-ProductPriceCalculatorApp – Tinker Console (2)](https://user-images.githubusercontent.com/1835883/208427281-192a6b26-60a8-4a9b-bf36-4ebcb48845da.png)

**Comment by Roboroads** [comment]
I changed the play icon for a green tinker icon, yes. I trhough that was more fun
