### ISSUE TITLE
Duplicate execution

### ISSUE THREAD

**Issue by Davidnadejdin** [Roboroads/laravel-tinker#23]
**Bug description**
Duplicate execution on windows

**To Reproduce**
Execute code

**Expected behavior**
Single execution

**Screenshots**
![image](https://user-images.githubusercontent.com/40993387/93726497-cdeec200-fbcf-11ea-9bd8-ba1caded755a.png)
![image](https://user-images.githubusercontent.com/40993387/93726518-e65edc80-fbcf-11ea-882e-3dd9c498ee49.png)

**Environment:**
 - IDE & Version:  PHPStorm 2020.2.1
 - PHP Version: 7.4.10
 - Laravel Tinker plugin version : 1.2.0
 - Interpreter Type: Local
 - Laravel Version: 8.0.0
 - Tinker version: 2.4.2

**Comment by Roboroads** [comment]
@Davidnadejdin Hey! Code is not executed twice, but displayed twice. I just had this problem myself.
Fixing this today!

**Comment by Roboroads** [comment]
Version 1.2.1 is submitted and in review - fixing this issue :smile:
