### ISSUE TITLE
Uncaught ErrorException: touch(): Utime failed: Invalid argument

### ISSUE THREAD

**Issue by amirzpr** [Roboroads/laravel-tinker#24]
Hi. I get an error with the message below, every time I execute a code in Tinker console. It doesn't matter what the statement is.

```
Uncaught ErrorException: touch(): Utime failed: Invalid argument in D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php:250
```

I've attached full error text as a text file for you.
[error.txt](https://github.com/Roboroads/laravel-tinker/files/5285354/error.txt)

**Environment:**
 - IDE & Version: PHPStorm 2020.2.1
 - PHP Version: 7.4.5
 - OS: Windows 10
 - Laravel Tinker plugin version : 1.2.0
 - Interpreter Type: Local
 - Laravel Version: 7.28.3
 - Tinker version: 2.4.2

I've also tried reinstalling the plugin, but it didn't help.

**Comment by Roboroads** [comment]
Hi @amirzpr - I need more information to know where this is coming from. Please use the bug template when creating an issue.

**Comment by amirzpr** [comment]
I've updated the issue according to bug template. @Roboroads

**Comment by Roboroads** [comment]
@amirzpr Thanks! Time to boot up the windows VM again huh - I already thought it was a windows problem.

**Comment by Roboroads** [comment]
@amirzpr Are you, by any chance, logged in with a user that has restricted access to the filesystem? (For instance, a windows Active Directory setup?)

**Comment by amirzpr** [comment]
No, I'm logged in as an Administrator user.

Yes. I've made some research about it. Isn't it related to the plugin? Because I'm not getting this error anywhere else.

**Comment by Roboroads** [comment]
@amirzpr It's in the way relaterd to the plugin that PsySH is trying to create a "hirstory file" - but since I don't really want to keep a history - since it's not needed and nothing gets written to it anyway - I tell PsySH to write to NUL on windows.

`$config->setHistoryFile(defined('PHP_WINDOWS_VERSION_BUILD') ? 'nul' : '/dev/null');`

**Comment by Roboroads** [comment]
Note that *not* setting a historyfile - PsySH created one itself. This is also unwanted.

**Comment by amirzpr** [comment]
Yes, I see.
Can you think of any solutions?! 🤔

**Comment by Roboroads** [comment]
Currently not - since i cannot edit PsySH - only what settings i put into it. Maybe put it in some kind of temp directory adn deleting it afterwards.. Seems hacky :man_shrugging:

**Comment by Roboroads** [comment]
@amirzpr could you maybe run the following commands in CMD on your PC and send me the output here?

 - `php -r "var_dump(defined('PHP_WINDOWS_VERSION_BUILD'));"`
 - `php -r "touch('nul');"`
 - `php -r "touch('\\nul');"`

**Comment by amirzpr** [comment]
> Currently not - since i cannot edit PsySH - only what settings i put into it. Maybe put it in some kind of temp directory adn deleting it afterwards.. Seems hacky 🤷‍♂️

Windows OS has a global temp directory. Maybe you could utilize that.


> @amirzpr could you maybe run the following commands in CMD on your PC and send me the output here?
> 
> * `php -r "var_dump(defined('PHP_WINDOWS_VERSION_BUILD'));"`
>   
>   * This will tell me if it actually is writing to nul and not to /dev/null
> * `php -r "touch('nul');"`
>   
>   * Will tell me if we can touch the nul file
> * `php -r "touch('\\nul');"`
>   
>   * Will tell me if we can touch the nul file if we prepend it with a slash
> * `php -r "touch(__DIR__ . '\\nul');"`
>   
>   * Will tell me if we can touch the nul file if we prepend it with the dir path
> 
> I'm asking you since I can't reproduce this on my windows VM 😅



Sure. Here are the results:

### Command:
```
php -r "var_dump(defined('PHP_WINDOWS_VERSION_BUILD'));"
```

### Output:
```
Command line code:1:
bool(true)
```

### Command:
```
php -r "touch('nul');"
```

### Output:
```
Warning: touch(): Utime failed: No error in Command line code on line 1

Call Stack:
    0.4025     392112   1. {main}() Command line code:0
    0.4025     392112   2. touch() Command line code:1
```

### Command:
```
php -r "touch('\\nul');"
```

### Output:
```
Warning: touch(): Utime failed: No error in Command line code on line 1

Call Stack:
    0.4025     392112   1. {main}() Command line code:0
    0.4025     392112   2. touch() Command line code:1
```


### Command:
```
php -r "touch(__DIR__ . '\\nul');"
```

### Output:
```
Warning: touch(): Utime failed: No error in Command line code on line 1

Call Stack:
    0.4028     392152   1. {main}() Command line code:0
    0.4028     392152   2. touch() Command line code:1
```

**Comment by Roboroads** [comment]
Thanks a lot!
Looks like the temp dir is going to be the only viable solution 🤷‍♂️

**Comment by amirzpr** [comment]
You're welcome. 💙
Please let me know if you fixed the issue.

**Comment by mortenscheel** [comment]
This issue looks very similar to https://github.com/spatie/laravel-web-tinker/issues/15
A fix has been merged in https://github.com/spatie/laravel-web-tinker/pull/42 which simply sets the history file to 'null' in stead of 'nul'. I hope it helps.

**Comment by mortenscheel** [comment]
I can confirm that changing 'nul' to 'null' fixes the issue on my Windows machine.
I have submitted https://github.com/Roboroads/laravel-tinker/pull/31 with the same fix as in https://github.com/spatie/laravel-web-tinker/pull/42

**Comment by Roboroads** [comment]
@mortenscheel See #11  why this fix doesn't work.

**Comment by mortenscheel** [comment]
@Roboroads Sorry I missed that. I've closed the PR.

Would it make sense to use XdgBaseDir\Xdg to get the path to the user's config folder and store the history there?

**Comment by Roboroads** [comment]
@mortenscheel Thing is that i really don't want a history I'm thinking about putting it in the system temp dir and deleting the file afterwards.

**Comment by mortenscheel** [comment]
Psysh has a Transient readline implementation that only stores history in memory (by setting useReadline to false). I don't know if that would be an option?

**Comment by Roboroads** [comment]
Hey, @amirzpr 

I probaby got a solution. I've compiled a test jar. If you can verify this works for you I can release it with v2.0.0

[Laravel Tinker-1.3.1-fix-attempt.zip](https://github.com/Roboroads/laravel-tinker/files/5944099/Laravel.Tinker-1.3.1-fix-attempt.zip)

**Comment by amirzpr** [comment]
Hey @Roboroads .
Thanks for that.

First of all, I have to say that I found out this specific problem just happens in one of my projects and the plugin works well in other projects!

Anyway, I installed and tested this jar file. The previous error is gone in the stated project. But now it's producing a new one which I paste its error text below.
Besides, after installing the jar, tinker console doesn't provide any output in projects that were working fine using the official version of the plugin.

```
   Symfony\Component\ErrorHandler\Error\FatalError 

  Uncaught ErrorException: Writing to php: is not allowed. in D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php:217
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(1024, 'Writing to php:...', 'D:\\www\\mosharek...', 217, Array)
#1 D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php(217): trigger_error('Writing to php:...', 1024)
#2 D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php(246): Psy\ConfigPaths::ensureDir('php:')
#3 D:\www\mosharekat-laravel\vendor\psy\psysh\src\Configuration.php(594): Psy\ConfigPaths::touchFileWithMkdir('php://temp')
#4 Command line code(32): Psy\Configuration->setHistoryFile('php://temp')
#5 {main}
  thrown

  at D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php:217
    213|             @\mkdir($dir, 0700, true);
    214|         }
    215| 
    216|         if (!\is_dir($dir) || !\is_writable($dir)) {
  > 217|             \trigger_error(\sprintf('Writing to %s is not allowed.', $dir), E_USER_NOTICE);
    218| 
    219|             return false;
    220|         }
    221|


   Whoops\Exception\ErrorException 

  Uncaught ErrorException: Writing to php: is not allowed. in D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php:217
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(1024, 'Writing to php:...', 'D:\\www\\mosharek...', 217, Array)
#1 D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php(217): trigger_error('Writing to php:...', 1024)
#2 D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php(246): Psy\ConfigPaths::ensureDir('php:')
#3 D:\www\mosharekat-laravel\vendor\psy\psysh\src\Configuration.php(594): Psy\ConfigPaths::touchFileWithMkdir('php://temp')
#4 Command line code(32): Psy\Configuration->setHistoryFile('php://temp')
#5 {main}
  thrown

  at D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php:217
    213|             @\mkdir($dir, 0700, true);
    214|         }
    215| 
    216|         if (!\is_dir($dir) || !\is_writable($dir)) {
  > 217|             \trigger_error(\sprintf('Writing to %s is not allowed.', $dir), E_USER_NOTICE);
    218| 
    219|             return false;
    220|         }
    221|

  1   D:\www\mosharekat-laravel\vendor\filp\whoops\src\Whoops\Run.php:408
      Whoops\Run::handleError("Uncaught ErrorException: Writing to php: is not allowed. in D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php:217
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(1024, 'Writing to php:...', 'D:\\www\\mosharek...', 217, Array)
#1 D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php(217): trigger_error('Writing to php:...', 1024)
#2 D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php(246): Psy\ConfigPaths::ensureDir('php:')
#3 D:\www\mosharekat-laravel\vendor\psy\psysh\src\Configuration.php(594): Psy\ConfigPaths::touchFileWithMkdir('php://temp')
#4 Command line code(32): Psy\Configuration->setHistoryFile('php://temp')
#5 {main}
  thrown", "D:\www\mosharekat-laravel\vendor\psy\psysh\src\ConfigPaths.php")

  2   [internal]:0
      Whoops\Run::handleShutdown()
*** Execution finished ***
```

**Comment by Roboroads** [comment]
@amirzpr Bummer - but i'm not giving up! 

I'm curious to why this project is special in writing rights to specific files. Do you run it om the same machine as the others? Maybe another php executable?

**Comment by amirzpr** [comment]
No, there is no environment differences between projects. All of them are even in the same folder and disk drive.

As much as I remember, I tried your plugin for the first time in this project.
After testing the plugin, when I wanted to commit the changes I've made in project using PhpStorm git commit dialog, I noticed a new file named `nul` in the project directory and I didn't know where it came from! So, I deleted the `nul` file from project directory sidebar of PhpStorm. Although, I think `nul` file is never exposed to user nor can be deleted or created, but I saw it, deleted it and after confronting the error, I tried to create `nul` file in the project directory, but the computer wouldn't allow that.

That was the whole story! Hope it helps you. 💙

**Comment by Roboroads** [comment]
@amirzpr You might confuse `nul` with `null` - since `null` is not a windows file driver (like `con` or `nul`). At first I wrote the history to '/dev/null' on unix and 'null' in windows. Then I updated the plugin because it made `null` files in windows.

Here I have a possible fix - tries to check for /dev/null, then nul, then system-tempdir/LTHisxxxx, lastly ./LTHisxxxx. On the last 2 options the file gets removed after executing.

So.. The fullest range of possibilities have been combed out this time! See my PR #44 to see what I tried :')

[Laravel Tinker-2.0.0-24-attempt.zip](https://github.com/Roboroads/laravel-tinker/files/5971937/Laravel.Tinker-2.0.0-24-attempt.zip)

**Comment by amirzpr** [comment]
![image](https://user-images.githubusercontent.com/45946337/107817207-124f4a00-6d8b-11eb-8476-7d41b41ced75.png)

No errors this time. 🎉
The error is gone. But there is no console output in any of the projects.
I used `echo` and `dd` to write to Tinker console, but the output is empty and only `*** Execution finished ***` shows up.

The speed is much better in this version btw. 👍

**Comment by leandrodiogenes** [comment]
Same here.

> ![image](https://user-images.githubusercontent.com/45946337/107817207-124f4a00-6d8b-11eb-8476-7d41b41ced75.png)
> 
> No errors this time. 🎉
> The error is gone. But there is no console output in any of the projects.
> I used `echo` and `dd` to write to Tinker console, but the output is empty and only `*** Execution finished ***` shows up.
> 
> The speed is much better in this version btw. 👍
