### ISSUE TITLE
Force save files before running tinker?

### ISSUE THREAD

**Issue by WilhelmH** [Roboroads/laravel-tinker#25]
Hello, and thank you for an excellent plugin!

**Bug description**
Changes in files not always recognized by tinker.

**To Reproduce**
Make some changes to a file (outside of Tinker Console) and run Laravel Tinker before files are automatically saved to disk.

**Expected behavior**
Run tinker _after_ all virutal files are saved to disk. Manually force saving files with CMD+S in PHP Storm before running seems to fix this.

**Environment (please complete the following information):**
 - IDE & Version: PHPStorm 2020.2.1
 - PHP Version: 7.3.7
 - Laravel Tinker plugin version : 1.2.0
 - Interpreter Type: Remote
 - Laravel Version: 6.0.1
 - Tinker version: 1.0.10

**Additional context**
First off, I can't 100% tell for sure if this is caused by IntelliJ not saving files immediately (or fast enough) to disk, but I do know IntelliJ stores changes in memory to 'virtual files' [before saving to disk](https://www.jetbrains.com/help/phpstorm/working-with-source-code.html#auto_save). That's why I suspect this is the issue, and also since force saving (CMD+S) solves the issue. I could be completely wrong though :) 

Is it possible to ensure all files are saved to disk before running tinker?

Again, thanks!

**Comment by Roboroads** [comment]
I'm unsure if i want to add this. I don't want to accidentally save someones file when in fact they didn't want that. I'm also unsure if a plugin can trigger a mass save. If it could, it could be a setting for the plugin.

Isn't there a setting that auto saves files when you unfocus the editor of that file?

**Comment by WilhelmH** [comment]
> I'm unsure if i want to add this. I don't want to accidentally save someones file when in fact they didn't want that.

PHPStorm is supposed to auto save files anyhow – you can't really turn it off, alt least not anymore. According to Peter Gromov: https://youtrack.jetbrains.com/issue/IDEABKL-6460#focus=Comments-27-366729.0-0

>  I'm also unsure if a plugin can trigger a mass save. If it could, it could be a setting for the plugin.

Would it be possible to listen to editor events for if a save occourred, or if a save is in progress? – and in which case, reload tinker, or something.
But a setting for it would be great though!

> Isn't there a setting that auto saves files when you unfocus the editor of that file?

Yes. According to their docs: "_Saving is triggered by various events, such as compiling, running, debugging, performing version control operations, closing a file or a project, or quitting the IDE._" But it doesn't always happen when I run Laravel Tinker.

One thing I forgot to mention though: I have the output window set to _View Mode_ > _Undock_. Maybe this doesn't trigger a save, somehow (in which case it would sound more like an IDE bug).

**Comment by Roboroads** [comment]
Hmm.. You are right. I'll see if I can implement this somehow when I have the time, or if you can't wait, add it yourself? :)

**Comment by WilhelmH** [comment]
Great! 

> ... or if you can't wait, add it yourself? :)

Unfortunately, I do not know how to develop plugins for IntelliJ, nor do I use Java/Kotlin, but I would love to do it someday!! :)

**Comment by Roboroads** [comment]
Bummer :man_shrugging: Haha

**Comment by Roboroads** [comment]
Version 1.2.1 is submitted and in review - fixing this issue :smile:

**Comment by WilhelmH** [comment]
Awesome! That was quick 😄

**Comment by Roboroads** [comment]
It was easier as expected 😊
