### ISSUE TITLE
[NOTICE] Class / File not found errors? Read this first!

### ISSUE THREAD

**Issue by Roboroads** [Roboroads/laravel-tinker#250]
Hey! Before you post a bug, please first check your interpreter settings. Most likely, your path mappings are incorrect and this has nothing to do with the plugin.

**Mounted volumes**

If you use a remote/docker interpreter, please make sure that your project is shared with the interpreter. The interpreter you are using also needs to have access to all the files of your project. Also make sure that the working directory of the interpreter is setup in the forlder where your project is located on the interpreter.

If you're using an interpreter via SSH, make sure your project is fully uploaded to the interpreter and stays in sync.

**Path mappings**

Then, if your project is mounted, please also make sure that the right directory in the interpreter is also mapped to the absolute path on the host to the absolute path on the interpreter. That way, Tinker knows where to find your project.

**Where to find this**

 - In PHPStorm, go to Settings -> PHP.
 - In other JB IDE's, PHP is found in settings under "Languages & Frameworks".

**Tinker Settings**

If you can't change the working directory or your vendor/laravel folder is located somewhere else, tou can force override the folder (of the interpreter) in the project settings of the tinker plugin. You can find those under Tools > Laravel Tinker > Project settings. 
 
 **Still having problems?**
 
 I doubt I can help you. These errors are 99,9% related to the interpreter settings - which Tinker uses to execute your PHP code.

**Comment by dennyweiss** [comment]
@Roboroads, as pointed out in #249, there is one additional case you could implement.

 `$app = require_once  __DIR__  .  $relativeCustomProjectDirectory  . '/bootstrap/app.php';
 
 But for this, you require an option that denotes that path of the plugin path input has to be treated as relative.
