### ISSUE TITLE
[Bug]: Arabic text is showing wrongly 

### ISSUE THREAD

**Issue by ObaydaAlesawi** [Roboroads/laravel-tinker#255]
### Short bug description

When I debug an Arabic text, it shows wrong

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

Debug an Arabic text let's say "مرحبا" and see what is showing.
![image](https://user-images.githubusercontent.com/32073999/236833780-3775a36b-5baa-46d1-b601-42c2054320c7.png)

### Expected behavior

Tinker should display the word as it is 

### Screenshots

![image](https://user-images.githubusercontent.com/32073999/236833816-91c9dbbc-37e7-4495-8125-6b0a1e476a27.png)

### IDE & Version

PHPstorm2023.1.1

### PHP Version

8.1

### OS and version

Windows 10

### Laravel Tinker plugin version

2.6

### Interpreter type

Local

### Laravel Version

9.52

### Tinker version

2.7

### Psysh version

0.11.2

**Comment by Roboroads** [comment]
![image](https://user-images.githubusercontent.com/4398301/236856831-2cad8459-5016-4f9a-94a8-39704929751b.png)

Might be a windows specific issue.. unsure yet..

**Comment by Algeneralo** [comment]
@Roboroads may I do anything that would help you?

**Comment by Roboroads** [comment]
> @Roboroads may I do anything that would help you?
> 

I'm not entirely sure yet what the problem is. I can't reproduce it on my linux system, the rest being the same. So, since the only difference the OS is, I have to test using Windows to flag this as unreproducible.

I did however remove something that was buggy, could you confirm when 6.2.1 comes out if the bug still persists? (Or, download the plugin from the release page and install manually to test)

**Comment by Algeneralo** [comment]
@Roboroads I've downloaded the last release https://github.com/Roboroads/laravel-tinker/releases/tag/v2.6.1 but it still has the same issue

**Comment by Roboroads** [comment]
@Algeneralo Auch. Thanks for testing tho. I'll see when I can spin up a windows to test it :)

**Comment by Algeneralo** [comment]
@Roboroads any updates on this?

**Comment by Algeneralo** [comment]
@Roboroads I can handle it no problem, do you have a starting point or an idea that may help me start debugging?

**Comment by kleczewsky** [comment]
I can confirm that polish letters are also being changed. Tinker in terminal works correct, but Laravel Tinker in phpstorm has this problem. 

Win 10
PhpStorm 2022.3.2
Plugin ver 2.6.1

**Comment by ZBrettonYe** [comment]
same with chinese letters

![image](https://github.com/Roboroads/laravel-tinker/assets/18015854/0cc49031-6b99-49a0-8d81-54f284d9b3c6)

**Comment by Algeneralo** [comment]
> 

Still need to be fixed

**Comment by 2rkmen** [comment]
![image](https://github.com/Roboroads/laravel-tinker/assets/8482586/c69fc198-08da-40ed-a437-9269c5486e82)

same with cyrillic

**Comment by Roboroads** [comment]
_Applies magic freshness_

**Comment by Roboroads** [comment]
Update about this - I've currently spent about 20 hours just trying to figure this out. I'm pretty sure it's an encoding issue but have no idea how to change it. It's a windows issue

I've posted in the JB Slack already - haven't had any useful response yet.

**Comment by x777o** [comment]
Hi guys. I encountered the same problem in Russian. Like echo "Привет"; I found out that **downgrading to 2.5.1 helps**. I think this is related to update 2.6 - specifically "Meta tag to set charset to UTF8 in toolwindow HTML."
Thanks to the author for his work!

**Comment by Algeneralo** [comment]
> Update about this - I've currently spent about 20 hours just trying to figure this out. I'm pretty sure it's an encoding issue but have no idea how to change it. It's a windows-only issue, that's what I do know (working on a windows VM is not working in favor of speed :P).
> 
> I've posted in the JB Slack already - haven't had any useful response yet.
> 
> Just know that I'm not ignoring this issue or anything, it's actually really hard to fix for some reason.

@Roboroads I'd be delighted to assist you with this matter, especially since I'm a Windows user and have encountered the same issue. Let's tackle this together

**Comment by Roboroads** [comment]
> Hi guys. I encountered the same problem in Russian. Like echo "Привет"; I found out that **downgrading to 2.5.1 helps**. I think this is related to update 2.6 - specifically "Meta tag to set charset to UTF8 in toolwindow HTML." Thanks to the author for his work!

@x777o Yea the 2.6 update I changed the way I;m rading from the console - applying colors on the kotlin side of the plugin. 't has nothing to do with the UFT8 marker, that was a way to try and fix this bug. 

Between 2.5 and 2.6 I changed the how colors are produced, from pattern matching the output to translating ANSI colors. This is where the problem lies: the JS side of things gives me the incorrectly encoded values from the windows terminal now and it's really annoying to debug why and what settings I can change.

>  I'd be delighted to assist you with this matter

@Algeneralo Hows your Java/Kotlin - because it's how JB is giving the plugin the output back.

**Comment by ObaydaAlesawi** [comment]
> > Hi guys. I encountered the same problem in Russian. Like echo "Привет"; I found out that **downgrading to 2.5.1 helps**. I think this is related to update 2.6 - specifically "Meta tag to set charset to UTF8 in toolwindow HTML." Thanks to the author for his work!
> 
> @x777o Yea the 2.6 update I changed the way I'm reading from the console - applying colors on the Kotlin side of the plugin. It has nothing to do with the UFT8 marker, that was a way to try and fix this bug.
> 
> Between 2.5 and 2.6 I changed the how the syntax highlighting is produced, from pattern matching the output to just using how tinker returns colors (ANSI) and translating those for more accurate highlighting. This is where the problem lies: the JB-side of things gives me the output encoded in windows-1252 (from the windows terminal, ofc) and it's really annoying to debug why and what settings I can change.
> 
> > I'd be delighted to assist you with this matter
> 
> @Algeneralo Hows your Java/Kotlin - because it's how JB is giving the plugin the output back.
> 
> EDIT: Typing this out actually gave me a new idea to try out - maybe on the PHP side, before outputting, I can encode all output into something unicode-only, and translate it back in the plugin.. Work in progress again!

I hope you've managed to find a solution?

**Comment by Roboroads** [comment]
Still a work in progress - I wish the JB plugin exosystem was a little more open :P
Also been sick the past 3 days, just got a litttle better and pikcing things back up slowly.

**Comment by Roboroads** [comment]
![image](https://github.com/Roboroads/laravel-tinker/assets/4398301/56b519f1-934e-4fd3-86c4-d587c55533b9)
This new idea is bearing fruits!

**Comment by Roboroads** [comment]
Update: GOT IT.

**Comment by Roboroads** [comment]
[Laravel Tinker-2.6.2-rc1.zip](https://github.com/Roboroads/laravel-tinker/files/14912392/Laravel.Tinker-2.6.2-rc1.zip)

Who wants to test it? Here'a a build that should fix this issue.
_plugins > [Cog-icon] > Install plugin from Disk.. > find the zip_

**Comment by 2rkmen** [comment]
![image](https://github.com/Roboroads/laravel-tinker/assets/8482586/07ffdff2-c244-49c9-bba4-c37115747c35)
windows 10 PhpStorm 2024.1 it works. Roboroads, thank you!!

**Comment by Roboroads** [comment]
> @Roboroads in #320  
> Hi all. I decided to revert back to 2.6 way of handling output. Release is pending into 2.7.1 and will be available for download shortly. This does mean that I will have to reopen #255 for the time being. Sorry windows users husing arabic/cyrillic text :(

Another way to fix this is a little dependant on JetBrains, as they promise me to respond and then don't. My current workaround is not working :(

**Comment by Roboroads** [comment]
Fixed again, tried another way which seems to work. Lmk if 2.7.2 is causing problems.
