### ISSUE TITLE
[Bug]: Tinker plugin in running on an external server instead of laravel instance.

### ISSUE THREAD

**Issue by CamKem** [Roboroads/laravel-tinker#264]
### Short bug description

When I run tinker plug it runs on https://3v4l.org/C4sr6 instead of locally

### Extended bug description

Today when I loaded up my tinker plugin, and typed some code I want to tinker with my local laravel instance, it is trying to run the code against `https://3v4l.org/C4sr6` this php multi-version thing. I just want it to run like it used to locally so it actually knows where my model classes are!.

Keeps giving me this error:

Fatal error: Uncaught Error: Class "App\Models\User" not found in /in/VS4m4:4
Stack trace:
#0 {main}
  thrown in /in/VS4m4 on line 4
<br/><i>Process exited with code <b title="Generic Error">255</b>.</i>

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

Open tinker console plugin in phpstorm.

Type in the code:
```
\App\Models\User::factory()->create();
```

Press run.

### Expected behavior

It should run the code locally like it used to know where the model classes are, instead it is doing some weird running on an external php server resource that doesn't seem to know laravel.

### IDE & Version

PhpStorm 2023.1.3

### PHP Version

8.2

### OS and version

MacOs 13.1 (22C65)

### Laravel Tinker plugin version

2.6.1

### Interpreter type

Local

### Laravel Version

10.13.5

### Tinker version

2.8.1

### Psysh version

v0.11.18

**Comment by CamKem** [comment]
My bad the UI has changed and I was clicking the wrong button.

**Comment by LiamKarlMitchell** [comment]
It looks like we use the "Run Console" button in the side gutter, not the normal kind of "Run" button at the top left next to "All versions".

![image](https://github.com/Roboroads/laravel-tinker/assets/1968109/2c1fbfcf-0154-4e4b-b729-7fab60db560e)


Recommend to improve the UI to add a select for  Run on configured PHP Interpreter or Run online "3v4l.org".

But why would developer want to run "Tinker" on a Remote website PHP Shell that does not have Laravel installed kind of weird...

It does seem to use the PHP in my docker container for laravel sail when I click that button or Ctrl+Shift+T.

**Comment by Roboroads** [comment]
Yea I'm sorry, JB did this change in recent versions of their IDE's and I havn't found a way to disable it yet

**Comment by PhillipMwaniki** [comment]
For context, the tinker console files are being detected as scratch files

<img width="1114" alt="image" src="https://github.com/Roboroads/laravel-tinker/assets/2037708/ec5ec845-dea4-46b9-bba9-40a64b6bbcf9">
