### ISSUE TITLE
Implement shortcut to run the code

### ISSUE THREAD

**Issue by fozbek** [Roboroads/laravel-tinker#27]
**Is your feature request related to a problem? Please describe.**
I don't prefer use mouse while coding. I think most people don't

**Describe the solution you'd like**
a shortcut to run the code

**Comment by Roboroads** [comment]
The shortcut to run the code is the same as the shortcut to open the tinker console. I have stated that everywhere where in tutorials and even in the description of the shortcut. Hope that helps you!

**Comment by fozbek** [comment]
Thanks.
