### ISSUE TITLE
[Bug]: PHP Fatal error:  Uncaught Error: Call to undefined method Psy\Configuration::setRawOutput() in Command line code:21

### ISSUE THREAD

**Issue by mmehdizadeh** [Roboroads/laravel-tinker#274]
### Short bug description

Run tinker on vagrant with Homestead

### Extended bug description

PHP Fatal error:  Uncaught Error: Call to undefined method Psy\Configuration::setRawOutput() in Command line code:21
Stack trace:
#0 {main}
  thrown in Command line code on line 21

   Symfony\Component\Debug\Exception\FatalErrorException  : Uncaught Error: Call to undefined method Psy\Configuration::setRawOutput() in Command line code:21
Stack trace:
#0 {main}
  thrown

  at Command line code:21

   Whoops\Exception\ErrorException  : Uncaught Error: Call to undefined method Psy\Configuration::setRawOutput() in Command line code:21
Stack trace:
#0 {main}
  thrown

  at Command line code:21

   Whoops\Exception\ErrorException  : file_get_contents(Command line code): failed to open stream: No such file or directory

  at /home/vagrant/code/project/vendor/filp/whoops/src/Whoops/Exception/Frame.php:120
    116|                 return null;
    117|             }
    118| 
    119|             try {
  > 120|                 $this->fileContentsCache = file_get_contents($filePath);
    121|             } catch (ErrorException $exception) {
    122|                 // Internal file paths of PHP extensions cannot be opened
    123|             }
    124|         }

  Exception trace:

  1   file_get_contents()
      /home/vagrant/code/project/vendor/filp/whoops/src/Whoops/Exception/Frame.php:120

  2   Whoops\Exception\Frame::getFileContents()
      /home/vagrant/code/project/vendor/nunomaduro/collision/src/Writer.php:217

  Please use the argument -v to see more details.

  Exception trace:

  1   Whoops\Run::handleError()
      /home/vagrant/code/project/vendor/filp/whoops/src/Whoops/Run.php:514

  2   Whoops\Run::handleShutdown()
      [internal]:0

*** Execution finished ***

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

Press Run

### Expected behavior

Dump model

### IDE & Version

PhpStorm 2023.1.1

### PHP Version

7.4

### OS and version

Arch

### Laravel Tinker plugin version

2.6.1

### Interpreter type

Local

### Laravel Version

6.20.44

### Tinker version

1.0.10

### Psysh version

0.9.12

**Comment by Roboroads** [comment]
_Applies magic freshness_

**Comment by Roboroads** [comment]
Asking the creator of Psysh iof they did something :)

**Comment by bobthecow** [comment]
There have been 30-40 releases of PsySH since the version cited in this ticket. We've almost certainly done something ¯\\\_(ツ)\_/¯

**Comment by Roboroads** [comment]
@mmehdizadeh Could you try and update tinker? Sorry, i fully missed this.
