### ISSUE TITLE
[Feature]: Format JSON output

### ISSUE THREAD

**Issue by satputekuldip** [Roboroads/laravel-tinker#276]
### My ideal solution

add a new feature that ensures output that are JSON are nicely formatted

### Intentions

- [ ] I'm open to build this myself and PR it

**Comment by Roboroads** [comment]
Excuse me for the late response.

Strings are strings - nothing I can do about them. If you want them to be pretty printed, concider using JSON_PRETTY_PRINT or just dumping your array.
