### ISSUE TITLE
[Bug]: Doesn't work when running on Laravel Sail

### ISSUE THREAD

**Issue by fenestron** [Roboroads/laravel-tinker#278]
### Short bug description

Unable to connect to DB when running with Laravel Sail

### Extended bug description

Application launched on Laravel Sail - https://laravel.com/docs/10.x/sail

![image](https://github.com/Roboroads/laravel-tinker/assets/9680621/f009863d-be32-4729-b14b-4636d3d5b9ac)

If I use Tinker from Sail everything works fine
![image](https://github.com/Roboroads/laravel-tinker/assets/9680621/4cbf1c3f-1f7e-4f3b-aa00-f992657db2ab)

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

1. Create a project with Laravel Sail
```
curl -s "https://laravel.build/example-app?with=pgsql,redis" | bash
cd example-app
sail up
```
2. Run the Laravel Tinker Plugin
```
<?php
use App\Models\User;
echo "123\n\n";
User::all();
```

### Expected behavior

Successful connection to the database. Display all users

### IDE & Version

PhpStorm 2023.2.1

### PHP Version

8.2.9

### OS and version

Ubuntu 22.04.3

### Laravel Tinker plugin version

2.6.1

### Interpreter type

Docker compose

### Laravel Version

10.20.0

### Tinker version

2.8.1

### Psysh version

0.11.20

**Comment by Roboroads** [comment]
Hey! 99.9% sure you are using a local interpreter to reach your docker database. That, indeed, does not work.

Check #250 :)
