### ISSUE TITLE
Trying to put a comment in the output?

### ISSUE THREAD

**Issue by Davidnadejdin** [Roboroads/laravel-tinker#28]
**To Reproduce**
Place a comment after an expression

**Expected behavior**
Ignore comment

**Screenshots**
![image](https://user-images.githubusercontent.com/40993387/95952055-dd4cde00-0e10-11eb-868d-dbfeccf53cd9.png)
![image](https://user-images.githubusercontent.com/40993387/95952078-e63daf80-0e10-11eb-9e42-efa52828c81e.png)

**Environment:**
 - IDE & Version: PHPStorm 2020.2
 - PHP Version: 7.4
 - OS: Windows 10
 - Laravel Tinker plugin version : 1.2.1
 - Interpreter Type: Local
 - Laravel Version: 8.9.0
 - Tinker version: 2.4.2

**Comment by Davidnadejdin** [comment]
@Roboroads the problem is in the tinker itself, you can clear the code from comments in this case, before passing it to the tinker

**Comment by Roboroads** [comment]
Ah yes. I'm not clearing comments before outputting them. I'll put it on the list 😊

**Comment by emargareten** [comment]
Anybody here? 👀

**Comment by Roboroads** [comment]
@emargareten Excuse me, I hadn't had the time to look at it at the time, and forgot about it afterwards. Checking it out now :smile:

**Comment by emargareten** [comment]
Thanks @Roboroads

**Comment by Roboroads** [comment]
Merged - will be in the next release (will prob. release one today with more fixes)
