### ISSUE TITLE
[Bug]: WSL

### ISSUE THREAD

**Issue by a-rehak** [Roboroads/laravel-tinker#281]
### Short bug description

When I try to run tinker from within docker container, it takes project path from wsl.

### Extended bug description

I have a setup where I am using Windows 10 and working on projects stored on a WSL Debian machine. Then I am running Docker desktop where I have my docker services with the development environment.

In phpstorm I have defined php interpreter from within the docker container and correct project mappings into the container. In the tools sectionm Laravel Tinker -  Project Settings I have to define the Laravel root folder and Vendor root folder. The problem is it wont take the folder path from "within" the container. It takes the path from within the WSL machine and it does not make path remapping correctly. So when trying to execute tinker code with PHP interpreter inside the docker container I get the:

```
// Laravel Tinker started at 2023-09-11 13:48:12
require(//wsl$/Debian/usr/local/src/company/ods-data-pump/vendor/autotoad.php): 
PHP Warning:
Failed to open stream: No such file or directory in Command line code on line 9
Uncaught Error: Failed opening required '//wsl$/Debian/usr/local/src/company/ods-data-pump/vendor/autotoad.php' . :/usr/share/php') in Command line code:9
Stack trace:
#0 {main}
thrown in Command line code on line 9
*** Execution finished
```
Which is correct because from within the docker container that parth does not exist....

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

1. Windows 10 machine
2. WSL Debian distro
3. Laravel projcet root stored on the WSL
4. Docker desktop installation
5. Laravel docker container with folder mapping into the docker container from within WSL
6. phpstorm configure php interpreter for the project inside the docker container
7. setup tinker plugin folder locations
8. try to execute any tinker code

### Expected behavior

Either tinker plugin will allow to specify folder locations from within the container or it will perform correct filepath transformations based on the interpreter path mappings.

### IDE & Version

PhpStorm 2023.2.1 Build #PS-232.9559.64, built on August 25, 2023

### PHP Version

8.2

### OS and version

Windows 10

### Laravel Tinker plugin version

2.6.1

### Interpreter type

Docker (NOT compose)

### Laravel Version

10.19

### Tinker version

v2.8.1

### Psysh version

v0.11.20

**Comment by Roboroads** [comment]
So, the settings feed these paths into the docker container. So, these path should be set the the path where your php files are located in the environment where PH is ran. In your case: within your docker container.

If you're using sail, it's probably `/var/www/html` and `/var/www/html/vendor`

**Comment by a-rehak** [comment]
@Roboroads ok so I changed the settings. Because the interpreter mappings is done in such a way that project root is mapped into the container, I have left the folder settings for the Tinker plugin empty.

Now I am getting:
![image](https://github.com/Roboroads/laravel-tinker/assets/54858156/f2a28f79-9563-4128-80bf-9627a7ec63de)

Despite having t he settings completelly empty:
![image](https://github.com/Roboroads/laravel-tinker/assets/54858156/220760d2-5b30-47fc-a64a-a5e434a53c63)

Notice the 2 leading slashes...

**Comment by a-rehak** [comment]
And if I specify for the Tinker plugin absolute path inside the container like this:
![image](https://github.com/Roboroads/laravel-tinker/assets/54858156/055e464b-50dd-4ea4-8ec5-b23379672306)

I get:
![image](https://github.com/Roboroads/laravel-tinker/assets/54858156/fd754561-d37d-4af5-8ac8-916d2312a06c)

**Comment by Roboroads** [comment]
Thanks! I'm going to take a look at it when I got the time. This indeed does not look right.

**Comment by Roboroads** [comment]
_Applies Freshness_

**Comment by JohnLeet** [comment]
@Roboroads I have the same issue
Windows 11
Wsl 2
Sail

It tried to run simple code `echo config('app.key')`

I got the error
![image](https://github.com/Roboroads/laravel-tinker/assets/143788518/1d5bcb36-08a3-4386-8508-be7e1ead028f)
Could help to solve the issue?

**Comment by Roboroads** [comment]
Is this still an issue with the new PHPStorm updates playing more nice with WSL?

**Comment by a-rehak** [comment]
I am sorry I am not using it anymore. I switched to another plugin.

**Comment by Roboroads** [comment]
Trying it myself locally with WSL works like intended. Probably, the WSL update of PHPStorm fixed this. If not, I would like to know :)
