### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by iron-viper** [Roboroads/laravel-tinker#290]
### Short bug description

Error after running

### Extended bug description

After starting, I see an error. Previously, everything worked

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

var_dump('111');

### Expected behavior

var dump

### Screenshots

![image](https://github.com/Roboroads/laravel-tinker/assets/1132974/61999e96-8fad-48f0-8d36-724e49e48482)
![image](https://github.com/Roboroads/laravel-tinker/assets/1132974/5e761220-c941-4a2e-ba6c-869f3edc5e92)

### IDE & Version

PHPStorm 2023.2.3

### PHP Version

8.1.25

### OS and version

Ubuntu 22

### Laravel Tinker plugin version

2.6.1

### Interpreter type

Local

### Laravel Version

10.28.0

### Tinker version

2.8.2

### Psysh version

0.11.22

**Comment by Roboroads** [comment]
And that file _does_ exist? `cat /home/alexandr/www/....../vendor/vendor/autoload.php`? (note the double vendor)

**Comment by iron-viper** [comment]
> And that file _does_ exist? `cat /home/alexandr/www/....../vendor/vendor/autoload.php`? (note the double vendor)

No. It doesn't exist.
![image](https://github.com/Roboroads/laravel-tinker/assets/1132974/5fad89d5-749b-4357-b0ed-5207125153ba)

**Comment by iron-viper** [comment]
Ohhhh, it's my mistake
Vendor root folder should be the same as Laravel root folder. Sorry, can be closet

**Comment by Roboroads** [comment]
Glad it's figured :smile:
