### ISSUE TITLE
Remove execution messages

### ISSUE THREAD

**Issue by emargareten** [Roboroads/laravel-tinker#30]
**Is your feature request related to a problem? Please describe.**
I think that the messages `// Laravel Tinker started at...` and `*** Execution finished ***` are to much in the way...

**Describe the solution you'd like**
remove the message or at least make it configurable

**Describe alternatives you've considered**
Move the messages to the bottom/right side or outside of the window 

**Additional context**
![image](https://user-images.githubusercontent.com/46111162/96128448-0ac38580-0efe-11eb-8a15-a49cfab06c78.png)

**Comment by Roboroads** [comment]
I guess making it configurable is a good idea.
