### ISSUE TITLE
[Bug]: ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by michabbb** [Roboroads/laravel-tinker#316]
### Short bug description

ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon

### Extended bug description

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'nl.deschepers.laraveltinker.action.OpenNewConsoleAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: nl.deschepers.laraveltinker]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

use phpstorm: 

PhpStorm 2024.1
Build #PS-241.14494.237, built on March 27, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0

### Expected behavior

no errors ;)

### IDE & Version

2024.1

### PHP Version

is not related to php

### OS and version

Windows 11

### Laravel Tinker plugin version

2.6.1

### Interpreter type

Docker (NOT compose)

### Laravel Version

not related to laravel

### Tinker version

not related to laravel

### Psysh version

not related to laravel

### Additional Context

This seems to be a global issue because the error gets thrown with starting phpstorm

**Comment by michabbb** [comment]
just fyi: donation done ✅ 😏

**Comment by Roboroads** [comment]
I've received notifications from JB as well that the prugin has some deprecations. Since they're catching up I see I got stuff to do xD

**Comment by michabbb** [comment]
Glad you are still on this plugin 🙏😊

**Comment by Roboroads** [comment]
Fixed in https://github.com/Roboroads/laravel-tinker/commit/8a4c5733dae1a064841f8b985c63570c65279599

**Comment by michabbb** [comment]
@Roboroads, when do you think we should see the new version in the phpstorm plugin store ??

**Comment by Roboroads** [comment]
@michabbb no news from jb yet. It's uploaded, waiting for approval :)
