### ISSUE TITLE
Error starting Tinker Query[Bug]: 

### ISSUE THREAD

**Issue by reinhardherrmann** [Roboroads/laravel-tinker#323]
### Short bug description

When starting query, the following issue occurs

### Extended bug description

Fatal error: Uncaught Error: Class "App\Models\User" not found in /in/ESCj2:2
Stack trace:
#0 {main}
  thrown in /in/ESCj2 on line 2
<br/><i>Process exited with code <b title="Generic Error">255</b>.</i>

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

\App\Models\User::all()->each();

### Expected behavior

show the user data

### IDE & Version

PHP Storm 2024.1

### PHP Version

8.3

### OS and version

Windows 11

### Laravel Tinker plugin version

2.7

### Interpreter type

Local

### Laravel Version

11

### Tinker version

2.7

### Psysh version

2.5.5

### Additional Context

nothing

**Comment by Roboroads** [comment]
Please check the [the FAQ](https://github.com/Roboroads/laravel-tinker/issues/250) and see if that solves your problem. Sounds like an interpreter thing.
