### ISSUE TITLE
[Feature]: Add option to set directory for saving.

### ISSUE THREAD

**Issue by wadud-eskimi** [Roboroads/laravel-tinker#325]
### Related problem

i use `docker-compose.yml` and i want to use this plugin but i am getting error `Could not open input file:`
and don't want to change `docker-compose.yml`

### My ideal solution

give a input option so i can set the directory where this new php file will be store.

### Intentions

- [ ] I'm open to build this myself and PR it

**Comment by Roboroads** [comment]
Please the [the FAQ](https://github.com/Roboroads/laravel-tinker/issues/250) and see if that solves your problem. Sounds like an interpreter thing.
