### ISSUE TITLE
Issues with PHPStorm Version 2023.1.5 Build #PS-231.9414.10 build on February 14,2024  Fatal error: Uncaught Error: Class "Illuminate\Support\Facades\DB" not found in /in/0g7nB:5

### ISSUE THREAD

**Issue by mydidefix** [Roboroads/laravel-tinker#333]
### Short bug description

The Database: Larvel 9.5  Query Builder not working

### Extended bug description

Fatal error: Uncaught Error: Class "Illuminate\Support\Facades\DB" not found in /in/0g7nB:5
Stack trace:
#0 {main}
  thrown in /in/0g7nB on line 5
<br/><i>Process exited with code <b title="Generic Error">255</b>.</i>

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

Trying to retrieve data from the users table. you get an error.

### Expected behavior

The query of the users table should work. It used to work as well.

### IDE & Version

PHPStorm 2023.1.5

### PHP Version

PHP 8.0.13 

### OS and version

OS

### Laravel Tinker plugin version

2.6.1

### Interpreter type

Local

### Laravel Version

versions : * v9.52.16

### Tinker version

* v2.8.2

### Psysh version

* v0.11.22

### Additional Context

The problem did not exist before laravel update.
I was able to access Laravel DB Query without any problems.
Fatal error: Uncaught Error: Class "Illuminate\Support\Facades\DB" not found in /in/0g7nB:5
Stack trace:
#0 {main}
  thrown in /in/0g7nB on line 5
<br/><i>Process exited with code <b title="Generic Error">255</b>.</i>

Many thanks for the great module.
mfg
Dieter

**Comment by Roboroads** [comment]
> thrown in /in/0g7nB

Looks like you're not running your code through tinker. 
The [the FAQ](https://github.com/Roboroads/laravel-tinker/issues/250)
