### ISSUE TITLE
[Bug]:The result output in the Tinker console contains characters in the wrong encoding (strange output)

### ISSUE THREAD

**Issue by jazz-max** [Roboroads/laravel-tinker#335]
### Short bug description

When I run tinker, his output window contains something in wrong encoding surrounding the result

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

type "hello world"
press run
look in result panel
<img width="446" alt="Снимок экрана 2024-05-09 в 12 42 00" src="https://github.com/Roboroads/laravel-tinker/assets/42142940/4185e063-b6ad-4f2f-9173-1072936a9edb">
<img width="452" alt="Снимок экрана 2024-05-09 в 12 41 46" src="https://github.com/Roboroads/laravel-tinker/assets/42142940/1d9d98c4-8461-41eb-8ea8-38df05524a1b">

### Expected behavior

all symbols must be readable 

### Screenshots

<img width="452" alt="Снимок экрана 2024-05-09 в 12 41 46" src="https://github.com/Roboroads/laravel-tinker/assets/42142940/2b6d0086-ab19-42ca-8d1d-1c945d7275ac">
<img width="446" alt="Снимок экрана 2024-05-09 в 12 42 00" src="https://github.com/Roboroads/laravel-tinker/assets/42142940/1ed33431-bc1d-4d5a-9ddf-3b8dc79f8687">

### IDE & Version

PhpStorm 2024.1

### PHP Version

PHP Version => 8.3.3-1+ubuntu22.04.1+deb.sury.org+1

### OS and version

macos 14.3 (23D56)

### Laravel Tinker plugin version

2.7.0

### Interpreter type

Docker compose

### Laravel Version

10.48.4

### Tinker version

2.9.0

### Psysh version

v0.12.2

**Comment by Roboroads** [comment]
Hey, thanks for posting this issue. It's related to https://github.com/Roboroads/laravel-tinker/issues/320 tho, so I'm going to close this one and focus it all there :)
