### ISSUE TITLE
[Bug]: "Strange" characters appear when running Tinker

### ISSUE THREAD

**Issue by dgcolumat** [Roboroads/laravel-tinker#338]
### Short bug description

When I run Tinker, "weird" characters appear in the output

### Extended bug description

Strange characters always appear instead of the results. Even if we do a simple "echo", the same characters always appear.
![image](https://github.com/Roboroads/laravel-tinker/assets/99033364/5bb1356c-11e3-4a1d-ba6f-35cf86588e46)

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

When I run anything.

### Expected behavior

The expected result should appear

### Screenshots

![image](https://github.com/Roboroads/laravel-tinker/assets/99033364/9702952a-bf9c-44f3-8524-1cdc8b508204)
![image](https://github.com/Roboroads/laravel-tinker/assets/99033364/a171f188-8235-42d1-a035-bce67116be01)

### IDE & Version

PHPStorm 2024.1

### PHP Version

8.0

### OS and version

Windows 11

### Laravel Tinker plugin version

2.7.0

### Interpreter type

Local

### Laravel Version

8.32

### Tinker version

2.7.0

### Psysh version

0.11.9

**Comment by dgcolumat** [comment]
When I install the @dev version of psysh, everything works normally.

**Comment by Roboroads** [comment]
Hey, thanks for posting this issue. It's related to https://github.com/Roboroads/laravel-tinker/issues/320 tho, so I'm going to close this one and focus it all there :)

**Comment by dgcolumat** [comment]
Ok, perfect! ;)
