### ISSUE TITLE
Tinker not working if the project root is not the laravel root

### ISSUE THREAD

**Issue by BazMaster** [Roboroads/laravel-tinker#34]
**Bug description**
```
PHP Fatal error:  Class 'App/Models/Link' not found in Psy Shell code on line 4
```

**To Reproduce**
I have Laravel located not in the root folder of the site, but in a subfolder. In one PhpStorm project, I have several Laravel sites.

It would be good to specify a path or several paths to the Laravel root folder in the settings.

Now this plugin is useless for me, unfortunately.

**Screenshots**
![image](https://user-images.githubusercontent.com/2923303/100182948-711cca00-2ee6-11eb-9a26-ac16d36ff36c.png)

**Environment (please complete the following information):**
 - IDE & Version: PHPStorm 2020.2.3
 - PHP Version: 7.3.16
 - OS: Windows 10
 - Laravel Tinker plugin version : 1.3.0
 - Interpreter Type: Local
 - Laravel Version: 8.15.0
 - Tinker version: v2.5.0

**Comment by BazMaster** [comment]
![image](https://user-images.githubusercontent.com/2923303/100183530-d6bd8600-2ee7-11eb-86e9-87ebab380cda.png)

I output the current folder in Tinker `print __DIR__`

Tinker links to the first site found by Laravel (`Games/ais_games` folder). 
But I'm working with the second one, which is located in the same PhpStorm project, but in a different folder: `Parsing/ais_parser`

**Comment by BazMaster** [comment]
![image](https://user-images.githubusercontent.com/2923303/100183878-c22dbd80-2ee8-11eb-9ebf-13a326b21da2.png)

Helped the exception of the first site from indexing PhpStorm. 
But it is better to do this through the settings.

**Comment by BazMaster** [comment]
I'm missing the following settings:

1. Specify the desired project that Tinker works with: https://github.com/Roboroads/laravel-tinker/issues/34
2. Line wrapping for Tinker Output.
3. Launch Tinker (in the Tinker Console) not only via the green Play icon, but also via the Ctrl+S keyboard shortcut.

----

I couldn't create a separate Issue (the button was disabled)
![image](https://user-images.githubusercontent.com/2923303/100184404-1ab18a80-2eea-11eb-8577-c2d4aec9c12e.png)

**Comment by Roboroads** [comment]
@BazMaster

For the original issue: Yes, I could see that as a problem. I'll make a setting where you can specify the laravel root.

For issue 2 - I've been trying to do that bot for some reason it's *really hard* to do. I could use some help with that from someone that has actual experience with Swing. I'll create an issue for this one.

For issue 3 - the shortcut you use to open the tinker shell (default Ctrl+shift+T) also runs it if you have the shell open. Does that fulfill yout needs?

**Comment by Roboroads** [comment]
@BazMaster You cannot create a new issue if you don't fill in the Title ;)

![image](https://user-images.githubusercontent.com/4398301/100234888-feced880-2f2b-11eb-9d0d-984dabd97d98.png)

**Comment by BazMaster** [comment]
Thank you, that's right.

1. Ok
2. Ok
3. Thank you. It works. (Ctrl+T)

I forgot the title - it was my inattention, I'm sorry.

**Comment by Roboroads** [comment]
@BazMaster excuse me it took so long, but you can now, in v2.2.0, set an execution root per-project. Hope this helps!
