### ISSUE TITLE
Add line wrapping option for tinker output

### ISSUE THREAD

**Issue by Roboroads** [Roboroads/laravel-tinker#35]
**Is your feature request related to a problem? Please describe.**
If the output contains a long string, you have to scroll. There's no line wrapping option.

**Describe the solution you'd like**
A line wrap option

Copied from [this issue by BazMaster](https://github.com/Roboroads/laravel-tinker/issues/34#issuecomment-733461645)

> Roboroads said: 
> I've been trying to do that but for some reason it's really hard to do. I could use some help with that from someone that has actual experience with Swing.

**Comment by Roboroads** [comment]
![image](https://user-images.githubusercontent.com/4398301/114168525-a6bfce00-9930-11eb-9e3d-72176881b63b.png)
Found a solution!

**Comment by rswfire** [comment]
So I'm a paid subscriber of Tinkerwell but I don't like using it in phpstorm because of this issue; I did the same thing op did and went with another solution. Please implement this -- horizontally scrolling through our output is really inconvenient.
