### ISSUE TITLE
[Bug]: No Output / Output vanishes with Version 2.7.3

### ISSUE THREAD

**Issue by baxt1yor** [Roboroads/laravel-tinker#353]
### Short bug description

laravel tinker version 2.7.3 my console doesn’t shows any output

### Extended bug description

After updating, my console shows output for a fraction of a second and after that the only output shown is:

`// Laravel Tinker started at 2024-07-04 09:40:59
*** Execution finished ***`

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

1. Open Tinker Console and dd something

### Expected behavior

Output shown in result window

### Screenshots

![image](https://github.com/Roboroads/laravel-tinker/assets/52046670/8c39b8e8-5257-4acc-8b62-4b923a13c46a)

### IDE & Version

PHPStorm 2024.1.4

### PHP Version

8.0

### OS and version

Windows 10

### Laravel Tinker plugin version

2.7.3

### Interpreter type

Local

### Laravel Version

8.0

### Tinker version

2.5

### Psysh version

^0.11.1|^0.12.0

**Comment by Roboroads** [comment]
Could you give me exact versions? As tinker 2.5 is not valid for psysh ^0.11.1

**Comment by Roboroads** [comment]
I just tested this on the following environment - guessing you copied the versions from composer.json and not the actual installed versions:

- Windows 10
- PHP 8.0.0 (local interpreter)
- Laravel v8.83.27
- Tinker plugin v2.7.3
- laravel/tinker v2.9.0
- psy/psysh v0.12.4

And I have zero issues
![image](https://github.com/user-attachments/assets/16807795-6c9a-429e-a5bb-ba181c1cffd6)

I need a way to reproduce the issue to fix it, as you know as co-developer, so I need more information here :)

**Comment by hesammoosapour** [comment]
I have the same problem here:
![image](https://github.com/user-attachments/assets/6543627f-cc29-4910-8a16-efa62a0e9158)

**Comment by Roboroads** [comment]
@hesammoosapour for your first one, don't return or print. Do it like you would with Tinker, JUST `\App\Models\User::all();` like your second one.

Then for the second one, that's an interpreter issue. Please check [the FAQ](https://github.com/Roboroads/laravel-tinker/issues/250)

**Comment by hesammoosapour** [comment]
It doesn't make any difference for me, same result! But If I do the same thing in a terminal, I get appropriate results!

**Comment by hesammoosapour** [comment]
![Uploading image.png…]()
![Uploading tinker.png…]()

**Comment by hesammoosapour** [comment]
I found the problem, my PHPStorm PHP Interpreter was set on a only pure PHP installed, once I changed it to xampp version that has other libraries etc, now it is working, thanks.

**Comment by pindab0ter** [comment]
> I found the solution, my PHPStorm PHP Interpreter was set on a only pure PHP installed, once I changed it to xampp version that has other libraries etc, now it is working, thanks.

This helped for me when I didn't get any errors to display.
