### ISSUE TITLE
Incompatible for PhpStorm 2020.3

### ISSUE THREAD

**Issue by emargareten** [Roboroads/laravel-tinker#36]
![image](https://user-images.githubusercontent.com/46111162/101044605-33740d00-3588-11eb-9b52-92e0e1b4c29e.png)

**Comment by Roboroads** [comment]
Fixed in https://github.com/Roboroads/laravel-tinker/releases/tag/v1.3.1 - which is now releasing :)

**Comment by emargareten** [comment]
Update is still waiting for JetBrains approval 😕

**Comment by Roboroads** [comment]
It is. I made a compatibitlity mistake somewhere so i had to re-upload it.
