### ISSUE TITLE
Add keyboard shortcut to execute statement under cursor

### ISSUE THREAD

**Issue by mortenscheel** [Roboroads/laravel-tinker#37]
The way you execute a statement in the Tinker console is very different from how similar plugins (e.g. Database console) does it.

**Describe the solution you'd like**
Phpstorm has a keybinding called "Execute Current Statement in Multiline Console". On Mac the default is CMD + Enter (I'm not sure about Windows/Linux). Pressing this keyboard shortcut should make Tinker console execute the code and show the result.

**Comment by Roboroads** [comment]
I'm unsure if I can easily hook into that event - but if I can figure it out I could add it :)

**Comment by Roboroads** [comment]
This is done, will be in the v2.0.0 release!
