### ISSUE TITLE
Provide an intention to "Execute in Tinker console"

### ISSUE THREAD

**Issue by mortenscheel** [Roboroads/laravel-tinker#38]
It would be awesome if it was possible to highlight a code snippet in a .php file, press ALT + Enter, and select "Execute in Tinker console".

**Comment by Roboroads** [comment]
That's an amazing idea - and i feel stupid for not thinking of this myself, haha.

**Comment by Roboroads** [comment]
This is done, will be in the v2.0.0 release!
