### ISSUE TITLE
No visible output

### ISSUE THREAD

**Issue by 949mac** [Roboroads/laravel-tinker#4]
What am I missing?

![image](https://user-images.githubusercontent.com/23151962/92137873-9061fa80-edc2-11ea-8411-588377c7fb2e.png)

**Comment by tm69** [comment]
you need to configure your php cli interpreter
Settings->Language & Frameworks->PHP

![imagen](https://user-images.githubusercontent.com/28063419/92151075-59491480-edd5-11ea-99fd-1206949737d5.png)

**Comment by Roboroads** [comment]
If it's not the interpreter settings please let me know. You should have received an error message with what the issue is but i could have missed an exception.

**Comment by Roboroads** [comment]
Also, quick hint, you can instead of this print_r thing also just do `\App\User::all();` without putting it in a variable to print it nicely immediately.

**Comment by matro-skin** [comment]
https://prnt.sc/ue69j5
How to change color?

**Comment by Roboroads** [comment]
@matro-skin tried to repair this in 1.1.1 but it seems a restart of the IDE fixes it for now. I created a new issue, #19 , I will tryu to make it work without a restart.

**Comment by qwertynik** [comment]
@Roboroads added a new issue #22 for output display format change

**Comment by Roboroads** [comment]
I'm going to assume the main issue got fixed.
