### ISSUE TITLE
Output window sometimes stops showing output

### ISSUE THREAD

**Issue by seifodev** [Roboroads/laravel-tinker#40]
![Screenshot_20201212_021141](https://user-images.githubusercontent.com/4215535/101966297-e810cd00-3c1f-11eb-8eb7-d8096de5b0fc.png)

when I first installed the plugin It worked fine and executed a query with large data.
after that when I try to execute any thing It gives me empty output 
when I reinstall the plugin, it works once then no output again.

Also large data output is incomplete.

**Comment by Roboroads** [comment]
Hey! I' m aware of this one, had it a couple of times myself.The workaround is closing the tinker output tab and then restsrting the ide. Excuse me for the inconveinience.I'm still trying for a fix ;)Op 12 dec. 2020 01:22 schreef Mahmoud Seifeldeen <notifications@github.com>:

when I first installed the plugin It worked fine and executed a query with large data.
after that when I try to execute any thing It gives me empty output
when I reinstall the plugin, it works once then no output again

**Comment by seifodev** [comment]
I really wish you could fix this soon, This plugin will make me abandon tinkerwell and tinkerpad.
Thanks

**Comment by Roboroads** [comment]
Please note that I don't have all the time and money to work on this free plugin. Working on this only brings satisfaction, no bread on the tabel (I wish..)😜 If it's urgent for you, you could try and PR this 🙂

**Comment by seifodev** [comment]
> Please note that I don't have all the time and money to work on this free plugin. Working on this only brings satisfaction, no bread on the tabel (I wish..)😜 If it's urgent for you, you could try and PR this 🙂

You are right and I really appreciate your work.
I can donate if it's possible because this plugin deserves

**Comment by swayok** [comment]
Got this problem when opened tinker in 2 IDE projects. 
In result all output was sent to the latest opened tinker output.

**Comment by Roboroads** [comment]
That can indeed be a problem - thanks for this info, now I can probably work this one out :D
