### ISSUE TITLE
Cannot debug with XDebug?

### ISSUE THREAD

**Issue by leandrodiogenes** [Roboroads/laravel-tinker#42]
**Bug description**
I`m using XDebug but i cant debug using tinker plugin. Anyone?

**Environment:**
 - IDE & Version: PHPStorm 2020.3.1
 - PHP Version: 7.4
 - OS: Windows 10
 - Laravel Tinker plugin version : 1.3.1
 - Interpreter Type: Local
 - Laravel Version: 8.20
 - Tinker version: 2.5.0

**Comment by Roboroads** [comment]
The plugin uses the interpreter you set up in your settings. Is xdebuig enabbled as plugin in those settings?
You could dump your ini settings in tinker to see if the xdebug plugin is enabled, maybe check your xdebug activation settings if they match.



Tinker works by asking the IDE “Using current interpreter settings, please execute this script” – so the plugin has nothing to do with PHP itself, that is all handled by your IDE.

**Comment by leandrodiogenes** [comment]
Yea, i think everything is ok.
I'm able to debug my tests and incoming requests but i'm not lucky on tinker plugin.


![image](https://user-images.githubusercontent.com/2463299/104107797-0e1ca200-529e-11eb-9532-0abcfd05ae5d.png)

This is my ini dump from laravel tinker output.
```
xdebug

xdebug support => enabled
Version => 2.9.5
Support Xdebug on Patreon, GitHub, or as a business: https://xdebug.org/support

Debugger => enabled
IDE Key => PHPSTORM

Directive => Local Value => Master Value
xdebug.auto_trace => Off => Off
xdebug.cli_color => 1 => 1
xdebug.collect_assignments => Off => Off
xdebug.collect_includes => On => On
xdebug.collect_params => 0 => 0
xdebug.collect_return => Off => Off
xdebug.collect_vars => Off => Off
xdebug.coverage_enable => On => On
xdebug.default_enable => On => On
xdebug.dump.COOKIE => no value => no value
xdebug.dump.ENV => no value => no value
xdebug.dump.FILES => no value => no value
xdebug.dump.GET => no value => no value
xdebug.dump.POST => no value => no value
xdebug.dump.REQUEST => no value => no value
xdebug.dump.SERVER => no value => no value
xdebug.dump.SESSION => no value => no value
xdebug.dump_globals => On => On
xdebug.dump_once => On => On
xdebug.dump_undefined => Off => Off
xdebug.file_link_format => no value => no value
xdebug.filename_format => no value => no value
xdebug.force_display_errors => Off => Off
xdebug.force_error_reporting => 0 => 0
xdebug.gc_stats_enable => Off => Off
xdebug.gc_stats_output_dir => C:\Windows\Temp => C:\Windows\Temp
xdebug.gc_stats_output_name => gcstats.%p => gcstats.%p
xdebug.halt_level => 0 => 0
xdebug.idekey => PHPSTORM => PHPSTORM
xdebug.max_nesting_level => 256 => 256
xdebug.max_stack_frames => -1 => -1
xdebug.overload_var_dump => 2 => 2
xdebug.profiler_append => Off => Off
xdebug.profiler_enable => Off => Off
xdebug.profiler_enable_trigger => Off => Off
xdebug.profiler_enable_trigger_value => no value => no value
xdebug.profiler_output_dir => C:\Windows\Temp => C:\Windows\Temp
xdebug.profiler_output_name => cachegrind.out.%p => cachegrind.out.%p
xdebug.remote_addr_header => no value => no value
xdebug.remote_autostart => On => On
xdebug.remote_connect_back => Off => Off
xdebug.remote_cookie_expire_time => 3600 => 3600
xdebug.remote_enable => On => On
xdebug.remote_host => 127.0.0.1 => 127.0.0.1
xdebug.remote_log => no value => no value
xdebug.remote_log_level => 7 => 7
xdebug.remote_mode => req => req
xdebug.remote_port => 9000 => 9000
xdebug.remote_timeout => 200 => 200
xdebug.scream => Off => Off
xdebug.show_error_trace => Off => Off
xdebug.show_exception_trace => Off => Off
xdebug.show_local_vars => On => On
xdebug.show_mem_delta => Off => Off
xdebug.trace_enable_trigger => Off => Off
xdebug.trace_enable_trigger_value => no value => no value
xdebug.trace_format => 0 => 0
xdebug.trace_options => 0 => 0
xdebug.trace_output_dir => C:\Windows\Temp => C:\Windows\Temp
xdebug.trace_output_name => trace.%c => trace.%c
xdebug.var_display_max_children => 128 => 128
xdebug.var_display_max_data => 512 => 512
xdebug.var_display_max_depth => 3 => 3```

**Comment by Roboroads** [comment]
Are  your tests running through the IDE interpreter as well? Looks like your xdebug is off when it uses the ini the IDE loads. Op 9 jan. 2021 21:15 schreef leandrodiogenes <notifications@github.com>:
Yea, i think everything is ok.
I'm able to debug my tests and incoming requests but i'm not lucky on tinker plugin.

This is my ini dump from laravel tinker output.
xdebug

xdebug support => enabled
Version => 2.9.5
Support Xdebug on Patreon, GitHub, or as a business: https://xdebug.org/support

Debugger => enabled
IDE Key => PHPSTORM

Directive => Local Value => Master Value
xdebug.auto_trace => Off => Off
xdebug.cli_color => 1 => 1
xdebug.collect_assignments => Off => Off
xdebug.collect_includes => On => On
xdebug.collect_params => 0 => 0
xdebug.collect_return => Off => Off
xdebug.collect_vars => Off => Off
xdebug.coverage_enable => On => On
xdebug.default_enable => On => On
xdebug.dump.COOKIE => no value => no value
xdebug.dump.ENV => no value => no value
xdebug.dump.FILES => no value => no value
xdebug.dump.GET => no value => no value
xdebug.dump.POST => no value => no value
xdebug.dump.REQUEST => no value => no value
xdebug.dump.SERVER => no value => no value
xdebug.dump.SESSION => no value => no value
xdebug.dump_globals => On => On
xdebug.dump_once => On => On
xdebug.dump_undefined => Off => Off
xdebug.file_link_format => no value => no value
xdebug.filename_format => no value => no value
xdebug.force_display_errors => Off => Off
xdebug.force_error_reporting => 0 => 0
xdebug.gc_stats_enable => Off => Off
xdebug.gc_stats_output_dir => C:\Windows\Temp => C:\Windows\Temp
xdebug.gc_stats_output_name => gcstats.%p => gcstats.%p
xdebug.halt_level => 0 => 0
xdebug.idekey => PHPSTORM => PHPSTORM
xdebug.max_nesting_level => 256 => 256
xdebug.max_stack_frames => -1 => -1
xdebug.overload_var_dump => 2 => 2
xdebug.profiler_append => Off => Off
xdebug.profiler_enable => Off => Off
xdebug.profiler_enable_trigger => Off => Off
xdebug.profiler_enable_trigger_value => no value => no value
xdebug.profiler_output_dir => C:\Windows\Temp => C:\Windows\Temp
xdebug.profiler_output_name => cachegrind.out.%p => cachegrind.out.%p
xdebug.remote_addr_header => no value => no value
xdebug.remote_autostart => On => On
xdebug.remote_connect_back => Off => Off
xdebug.remote_cookie_expire_time => 3600 => 3600
xdebug.remote_enable => On => On
xdebug.remote_host => 127.0.0.1 => 127.0.0.1
xdebug.remote_log => no value => no value
xdebug.remote_log_level => 7 => 7
xdebug.remote_mode => req => req
xdebug.remote_port => 9000 => 9000
xdebug.remote_timeout => 200 => 200
xdebug.scream => Off => Off
xdebug.show_error_trace => Off => Off
xdebug.show_exception_trace => Off => Off
xdebug.show_local_vars => On => On
xdebug.show_mem_delta => Off => Off
xdebug.trace_enable_trigger => Off => Off
xdebug.trace_enable_trigger_value => no value => no value
xdebug.trace_format => 0 => 0
xdebug.trace_options => 0 => 0
xdebug.trace_output_dir => C:\Windows\Temp => C:\Windows\Temp
xdebug.trace_output_name => trace.%c => trace.%c
xdebug.var_display_max_children => 128 => 128
xdebug.var_display_max_data => 512 => 512
xdebug.var_display_max_depth => 3 => 3```

**Comment by leandrodiogenes** [comment]
Yea, i'm running my test throughs PHPSTORM.
Everything is debugging fine, tests, income requests and artisan tinker terminal commands.

**Comment by Roboroads** [comment]
Alright. I've gotten the time to check out how I can get it running for myself - I'll let you know!

**Comment by Roboroads** [comment]
I see -  i'm doing a PhpScriptRun instead of some debug session - Run and Debug configs are different. I'm unsure as to how I can set up a debug run yet.

**Comment by Sentoki** [comment]
Agree with @atymic it would be great

**Comment by afpinedac** [comment]
I was able to set up the debugger by adding at the beginning the require(PATH_TO_THE_LARAVEL_INDEX) in order to load the entire app and in the debug set up just simply run it as a script. The breakpoints are working :) 

![image](https://github.com/Roboroads/laravel-tinker/assets/3707188/bfd69460-0396-4af9-8dee-ae53f04172cc)

**Comment by leandrodiogenes** [comment]
Awesome @afpinedac thanks buddy it works great.

**Comment by Roboroads** [comment]
As @leandrodiogenes sais, this is not running the tinker plugin :P

The only way I can see this working is if I'm going to create files in your project (like a .tinkertmp/somefile.php) with your console code in it.

Step debugging should work tho - it just does not work within the tinker console. Having a breakpoint inside of a file in your project should work theoretically, since Tinker does start with debugging on. So, fingers crossed :x
