### ISSUE TITLE
Tinker output does not show '<' symbol unless wrapped with htmlentities('<') 

### ISSUE THREAD

**Issue by swayok** [Roboroads/laravel-tinker#47]
**Bug description**
Write here a clear and concise description of what the bug is.
Tinker output does not show `<` symbol unless wrapped with `htmlentities('<')`

**To Reproduce**
What did you do to encounter the bug?
`echo '<'`
`echo '<tag>'`

**Expected behavior**
If the description didn't make it clear enough, what should have happened?
`<` printed

**Environment (please complete the following information):**
 - IDE & Version: PHPStorm 2020.3
 - PHP Version: 7.4
 - OS: Windows 10
 - Laravel Tinker plugin version : 2.0.0
 - Interpreter Type: Local 
 - Laravel Version: 5.7 and 8.0
 - Tinker version: 1.0.10 and 2.5.0

**Additional context**
It seems like output handled as HTML which is quite unexpected in case of Tinker usage.

**Comment by Roboroads** [comment]
> It seems like output handled as HTML which is quite unexpected in case of Tinker usage.

True, the output is parsed as HTML - I'll look into this one.
