### ISSUE TITLE
Couple of feature requests

### ISSUE THREAD

**Issue by Evertt** [Roboroads/laravel-tinker#5]
- Being able to run the code with a simple keyboard shortcut. If that already exists, then please document that somewhere.
- Maybe also being able to turn on "auto-run" which runs your code automatically whenever you stop typing for a second?
- Making the output window prettier.
    - Like using the same font as the user has configured for their editor.
    - And some form of syntax highlighting in the output window would also be very nice. (Tinkerwell does this and it's very pleasant to look at.)

Mostly though, I really love this plugin, thank you for making it. 🙏

**Comment by Roboroads** [comment]
You can run the code with the same keystroke as you use to open it (ctrl shift T is default). This is documented everywhere :P

I thought about autorunning but if you are writing delete queries and ot runs automatically before you wrote the "where" part this feature does more harm than good.

Output window is indeed not the nicest right now. I tried a couple different things and this was the best for now. I dont know how to get the user defaults yet :P

Thanks for the feedback! And you are welcome.

**Comment by Evertt** [comment]
> You can run the code with the same keystroke as you use to open it (ctrl shift T is default). This is documented everywhere :P

In the readme I read:

> Open/Run the console under Tools -> Run Tinker Console
> 
> Default shortcut: ctrl+Shift+T

So I understood from that that I could open the console with that shortcut. It was not clear to me however that that shortcut can also run the code.

> I thought about autorunning but if you are writing delete queries and ot runs automatically before you wrote the "where" part this feature does more harm than good.

Good point. I wasn't super sure about that feature already, but now I fully agree that that wouldn't be a good idea. 😅

> Output window is indeed not the nicest right now. I tried a couple different things and this was the best for now. I dont know how to get the user defaults yet :P

Okay cool, I understand. :-)

**Comment by Roboroads** [comment]
> So I understood from that that I could open the console with that shortcut. It was not clear to me however that that shortcut can also run the code.

I'll clear that up in the readme for the next release - that's what the "run" means. The shortcut checks if you have a console open, if not it opens one, if yes it runs it.

**Comment by Roboroads** [comment]
I've splitted feature requests into individual ones. Thanks for your feedback!
