### ISSUE TITLE
Tinker Running Code From Previous Console

### ISSUE THREAD

**Issue by Blue-Kachina** [Roboroads/laravel-tinker#52]
**Bug description**
After having just upgraded to v2.0.1, I'm finding that the Laravel Tinker plugin will sometimes run code from a previous Tinker Console

**To Reproduce**
1. Ran simple code like "Hello World"
2. Tools>Laravel Tinker>Close All Tinker Windows
3. Deleted old Laravel Tinker Console(s) from Scratches and Consoles
4. Tools>Laravel Tinker>Open New Console
5. Typed out and ran new code
6. Tinker Output shows output that I would've expected from console in step 1

**Expected behavior**
Tinker Output would show output from console in step 5

**Screenshots**
[Screenshot](https://pasteboard.co/JUghaEe.png)

**Environment (please complete the following information):**
 - IDE & Version: PHPStorm 2020.3.3
 - PHP Version: v7.4.1
 - OS: Windows 10
 - Laravel Tinker plugin version : 2.0.1
 - Interpreter Type: Local
 - Laravel Version: v8.32.1
 - Tinker version: v2.6.1

**Additional context**
This started happening after upgrade to v2.0.1 of plugin

**Comment by Roboroads** [comment]
Hi, I've done your exact reproduction steps without success. Do you have multiple projects open by any chance?

**Comment by Blue-Kachina** [comment]
@Roboroads 
The timestamp in the console was indeed changing.
I did not have multiple projects open at the time.
I had just installed the update for your plugin though, and perhaps I had just needed to restart PHPStorm or something. 
This problem has not happened again since reporting it.

**Comment by Roboroads** [comment]
Alright! I will keep.the issue open for a little while, to see if the problem appears for someone else and will otherwise close it.Thanks for helping!
