### ISSUE TITLE
Adaptation to lumen

### ISSUE THREAD

**Issue by ZHOUXING1997** [Roboroads/laravel-tinker#58]
Hello, can we make it work with the Lumen？

**Comment by Roboroads** [comment]
I'm not sure. Have you tried installing tinker and just running it? `composer require --dev laravel/tinker`

**Comment by ZHOUXING1997** [comment]
是的，我已经安装过，并且运行过了。我的框架版本：Lumen8.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Roboroads/laravel-tinker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月16日(星期三) 晚上6:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Roboroads/laravel-tinker] Adaptation to lumen (#58)





 
I'm not sure. Have you tried installing tinker and just running it? composer require --dev laravel/tinker

**Comment by Roboroads** [comment]
"Yes, I have installed it and it has been running. My frame version Lumen8.0" (translated with google)

So, if it's working, i will close this :)

**Comment by ZHOUXING1997** [comment]
好的，感谢您的回复。
我的运行结果





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Roboroads/laravel-tinker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月16日(星期三) 晚上10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Roboroads/laravel-tinker] Adaptation to lumen (#58)





 
"Yes, I have installed it and it has been running. My frame version Lumen8.0" (translated with google)
 
So, if it's working, i will close this :)
