### ISSUE TITLE
Use the same font/color as in the rest of the IDE

### ISSUE THREAD

**Issue by Roboroads** [Roboroads/laravel-tinker#6]
As @Evertt pointed out in #5 the output window could be prettier

**Comment by qwertynik** [comment]
@Roboroads I agree with @Evertt, this will make it more easily usable. Currently I am unable to see the output. Running a dark them on PHPStorm on a Windows 10 machine. 
Eagerly waiting for this.

**Comment by Roboroads** [comment]
@qwertynik actually already working on it. Should be done today.

**Comment by Roboroads** [comment]
Added to v1.1.1 - will release today

**Comment by TobiasGasser** [comment]
Using the Darcula default theme. The "Tinker Output" font color always is black though and is barely visible.
Anything I missed?

**Comment by Roboroads** [comment]
After switching you have to restart.Op 8 sep. 2020 13:27 schreef Tobias Gasser <notifications@github.com>:
Using the Darcula default theme. The "Tinker Output" font color always is black though and is barely visible.
Anything I missed?

**Comment by TobiasGasser** [comment]
Works, thanks! - Could have come to my mind myself.... ;)

**Comment by Roboroads** [comment]
@TobiasGasser @qwertynik @Evertt How is the output window for you now? Is it better than what it was?

**Comment by Evertt** [comment]
I updated to the last version (1.1.1), restarted PhpStorm and yet I see no difference. I don't know what I'm doing wrong.

![image](https://user-images.githubusercontent.com/1267282/92570581-5ee5a500-f282-11ea-8509-9d29db1ca256.png)

**Comment by TobiasGasser** [comment]
After initial restart it actually did not work (same screen as @Evertt ).
Had to restart again, then it worked.

**Comment by qwertynik** [comment]
@Roboroads 
Hey, thanks for being responsive and upgrading the extension. Tried restarting did not help. Restarted again as per @TobiasGasser's suggestion and now it is much better.

![image](https://user-images.githubusercontent.com/6836536/93561485-e6799500-f9a1-11ea-9bde-7289b985f3b4.png)

Would be great if there is an option to increase the font size in the output.

**Comment by Roboroads** [comment]
@qwertynik plugin v1.2.0 just got approved in which the problem gets solved. You should update 😊

Increasing the font size would be a new feature (or it should follow the ide settings as well) - best make a new issue for that one.
