### ISSUE TITLE
Add syntax highlighting in the output

### ISSUE THREAD

**Issue by Roboroads** [Roboroads/laravel-tinker#7]
As @Evertt pointed out in #5 the output should be syntax highlighted

**Comment by Roboroads** [comment]
@Evertt How's this?

![image](https://user-images.githubusercontent.com/4398301/93379362-01db8780-f85e-11ea-9dc6-ebaf6ab10024.png)

**Comment by Roboroads** [comment]
Got it now following IDE style automatically
![image](https://user-images.githubusercontent.com/4398301/93381771-706e1480-f861-11ea-8401-23c30e196fda.png)
![image](https://user-images.githubusercontent.com/4398301/93381795-79f77c80-f861-11ea-8ec6-16f9dfe6a857.png)

**Comment by Evertt** [comment]
Awesome
